// @ts-nocheck
// ── examSummaryQuestionsEngine.ts ────────────────────────────────
// CONTENT ONLY — Engine variant of the 13th exam ("Foundation Summary"),
// drafted 2026-09-06 per explicit user validation of the 6-theme plan
// (theme 1 sample validated first, themes 2-6 generalized on the same
// model, then translated to 4 languages). This file is NOT imported or
// wired anywhere yet (no page, no unlock logic, no examQuestionPools.ts
// integration) — same status as examSummaryQuestions.ts (the Deck
// variant) at its own creation. Per standing doctrine, content approval
// is not approval to build engine/UI. That is a separate, explicitly
// gated next step (hook, page, COMPETENCIES_FOUNDATION_SUMMARY_ENGINE,
// department-conditional routing on the Dashboard).
//
// Doctrine applied to theme 3 (MARPOL Annex I obligations), same as the
// Deck file: the regulatory CONCEPT is tested and convention names
// (MARPOL, Annex I) are referenced directly, but no authority is
// attributed to the organization itself — no "according to IMO", no bare
// "IMO"/"OMI" acronym anywhere in this file.
//
// Each theme is a single cross-domain scenario spanning 3-4 already-taught
// Engine/Safety(s1e) modules, testing synthesis and prioritization under
// pressure — not re-testing facts already covered by each module's own
// mini-exam. s1e (Engine Room Resource Management) plays the same
// connective role here that s1 plays in the Deck version: every theme
// tests a decision-under-pressure reflex (hesitation to escalate,
// technical caution before acting, post-event reassessment) alongside the
// factual Engine content. 20 questions total across 6 themes (4+3+3+3+4+3),
// quadrilingual — same envelope as the Deck version, by explicit user
// decision to keep parity rather than adjust the format.

const LANGS = ["fr", "en", "es", "pt"];

export const SUMMARY_THEMES_META_ENGINE = [
  { id: "theme1_engine_blackout", modules: ["e1", "e2", "e7", "s1e"] },
  { id: "theme2_engine_room_fire", modules: ["e1", "s4", "s1e", "s6"] },
  { id: "theme3_marpol_pressure", modules: ["e4", "e2", "s6"] },
  { id: "theme4_medical_engine_space", modules: ["s3", "s1e", "e1"] },
  { id: "theme5_abandon_ship_engine", modules: ["s5", "s1e", "e1"] },
  { id: "theme6_ums_alarm_response", modules: ["e7", "s1e", "e3", "e6"] },
];

export const SUMMARY_QUESTIONS_ENGINE = {
  // ══════════════════════════════════════
  // THEME 1 — Engine blackout & loss of propulsion
  // (Propulsion + Electrical + UMS + ERM decision reflex)
  // ══════════════════════════════════════
  theme1_engine_blackout: {
    fr: [
      { q:"Vous êtes de quart en salle des machines en zone de navigation restreinte (chenal étroit / trafic dense). Un générateur principal se déclenche brutalement, entraînant une perte de tableau principal et donc de la propulsion (blackout). Quelle est votre priorité immédiate ?", opts:["Attendre que le groupe électrogène redémarre seul avant d'agir","Démarrer immédiatement le groupe de secours (emergency generator) pour rétablir l'alimentation critique, tout en informant la passerelle sans délai","Diagnostiquer d'abord la cause exacte du déclenchement avant toute action de rétablissement","Attendre l'arrivée du Chef Mécanicien avant toute manœuvre"], correct:1, expl:"Un blackout en zone de navigation restreinte est une urgence à double dimension : rétablir l'alimentation critique (groupe de secours) est la priorité immédiate, en parallèle d'une information sans délai à la passerelle puisque le navire est sans propulsion — le diagnostic complet de la cause vient après la sécurisation immédiate." },
      { q:"Le groupe électrogène de secours démarre, mais vous savez qu'il a récemment présenté une anomalie de refroidissement non totalement résolue. La pression pour rétablir la propulsion au plus vite est forte. Que devez-vous garder à l'esprit avant de le pousser à pleine charge immédiatement ?", opts:["Rien de particulier, rétablir la propulsion prime toujours sans réserve","Une montée en charge trop rapide sur un groupe fragilisé peut provoquer une seconde panne critique — la remise en service doit rester progressive et surveillée, même sous pression de temps","Il faut d'abord vidanger complètement le circuit de refroidissement avant tout redémarrage","L'anomalie de refroidissement n'a aucun lien avec la charge appliquée au groupe"], correct:1, expl:"Un groupe déjà fragilisé impose une montée en charge progressive et surveillée, même si le rétablissement de la propulsion reste non négociable — une charge brutale sur un équipement affaibli peut transformer une panne gérable en avarie plus grave, voire en perte totale de la source de secours." },
      { q:"Vous êtes l'officier machine de quart au moment du blackout. Vous pensez pouvoir rétablir la situation seul avant que cela ne s'aggrave, et hésitez à appeler immédiatement le Chef Mécanicien. Quel réflexe ERM s'applique ici ?", opts:["Continuer seul, réveiller le Chef Mécanicien pour un incident que vous pensez maîtriser serait mal vu","Alerter immédiatement le Chef Mécanicien et la passerelle — un blackout est par nature un événement à ressources partagées, et l'hésitation à solliciter de l'aide est précisément le biais que l'ERM cherche à corriger","Attendre que la situation s'aggrave encore pour être certain que l'appel est justifié","Résoudre d'abord complètement le problème électrique avant de mentionner l'incident à qui que ce soit"], correct:1, expl:"L'ERM identifie précisément cette hésitation hiérarchique comme un facteur de risque : un blackout mobilise potentiellement toute l'équipe machine et affecte directement la sécurité de navigation — l'alerte immédiate au Chef Mécanicien et à la passerelle n'est jamais une option secondaire." },
      { q:"L'alimentation est rétablie via le groupe de secours et la propulsion est de nouveau disponible. L'urgence immédiate semble résolue. Quelle est la bonne pratique à ce stade ?", opts:["Considérer l'incident clos et remettre le groupe principal en service sans investigation","Poursuivre la surveillance et investiguer la cause racine du déclenchement avant tout retour à la configuration normale — la fin du blackout ne signifie pas la fin du risque de récidive","Arrêter le groupe de secours immédiatement pour économiser le carburant","Ignorer l'incident dans le registre puisque la situation est rétablie"], correct:1, expl:"Comme pour toute avarie critique, la réévaluation continue reste indispensable : rétablir l'alimentation ne remplace pas le diagnostic de la cause racine, et reprendre la configuration normale sans investigation expose à une récidive du même incident." },
    ],
    en: [
      { q:"You are on watch in the engine room in a restricted navigation area (narrow channel / dense traffic). A main generator trips suddenly, causing a loss of the main switchboard and therefore of propulsion (blackout). What is your immediate priority?", opts:["Wait for the generator to restart on its own before acting","Immediately start the emergency generator to restore critical power, while informing the bridge without delay","Diagnose the exact cause of the trip first before any restoration action","Wait for the Chief Engineer to arrive before any action"], correct:1, expl:"A blackout in a restricted navigation area is a two-dimensional emergency: restoring critical power (emergency generator) is the immediate priority, alongside informing the bridge without delay since the vessel has no propulsion — full diagnosis of the cause comes after immediate safety measures." },
      { q:"The emergency generator starts, but you know it recently had an unresolved cooling anomaly. There is strong pressure to restore propulsion as fast as possible. What must you keep in mind before pushing it to full load immediately?", opts:["Nothing in particular, restoring propulsion always takes priority without reservation","Loading a weakened generator too quickly can cause a second critical failure — bringing it back into service must remain gradual and monitored, even under time pressure","The cooling circuit must be fully drained before any restart","The cooling anomaly has no connection to the load applied to the generator"], correct:1, expl:"An already weakened generator requires a gradual, monitored load increase, even though restoring propulsion remains non-negotiable — an abrupt load on a weakened unit can turn a manageable failure into a more serious casualty, or even total loss of the emergency source." },
      { q:"You are the engineer of the watch at the moment of the blackout. You think you can restore the situation alone before it worsens, and hesitate to call the Chief Engineer immediately. Which ERM reflex applies here?", opts:["Continue alone, waking the Chief Engineer for an incident you think you can handle would be poorly received","Immediately alert the Chief Engineer and the bridge — a blackout is by nature a shared-resource event, and hesitating to seek help is exactly the bias ERM aims to correct","Wait for the situation to worsen further to be certain the call is justified","Fully resolve the electrical problem first before mentioning the incident to anyone"], correct:1, expl:"ERM specifically identifies this hierarchical hesitation as a risk factor: a blackout potentially mobilizes the entire engine team and directly affects navigational safety — immediately alerting the Chief Engineer and the bridge is never a secondary option." },
      { q:"Power is restored via the emergency generator and propulsion is available again. The immediate emergency seems resolved. What is the correct practice at this stage?", opts:["Consider the incident closed and put the main generator back into service without investigation","Continue monitoring and investigate the root cause of the trip before returning to normal configuration — the end of the blackout does not mean the end of the risk of recurrence","Shut down the emergency generator immediately to save fuel","Skip logging the incident since the situation is restored"], correct:1, expl:"As with any critical casualty, continuous reassessment remains essential: restoring power does not replace diagnosing the root cause, and returning to normal configuration without investigation risks a recurrence of the same incident." },
    ],
    es: [
      { q:"Estás de guardia en la sala de máquinas en una zona de navegación restringida (canal estrecho / tráfico denso). Un generador principal se dispara bruscamente, provocando la pérdida del cuadro principal y, por tanto, de la propulsión (blackout). ¿Cuál es tu prioridad inmediata?", opts:["Esperar a que el generador arranque solo antes de actuar","Arrancar de inmediato el generador de emergencia para restablecer la alimentación crítica, informando sin demora al puente","Diagnosticar primero la causa exacta del disparo antes de cualquier acción de restablecimiento","Esperar la llegada del Jefe de Máquinas antes de cualquier maniobra"], correct:1, expl:"Un blackout en una zona de navegación restringida es una emergencia de doble dimensión: restablecer la alimentación crítica (generador de emergencia) es la prioridad inmediata, junto con informar sin demora al puente ya que el buque está sin propulsión — el diagnóstico completo de la causa llega después de la seguridad inmediata." },
      { q:"El generador de emergencia arranca, pero sabes que recientemente presentó una anomalía de refrigeración no totalmente resuelta. La presión por restablecer la propulsión cuanto antes es fuerte. ¿Qué debes tener presente antes de llevarlo a plena carga de inmediato?", opts:["Nada en particular, restablecer la propulsión siempre prevalece sin reserva","Una subida de carga demasiado rápida en un grupo debilitado puede provocar una segunda avería crítica — la puesta en servicio debe seguir siendo progresiva y vigilada, incluso bajo presión de tiempo","Hay que vaciar completamente el circuito de refrigeración antes de cualquier arranque","La anomalía de refrigeración no tiene relación alguna con la carga aplicada al grupo"], correct:1, expl:"Un grupo ya debilitado exige una subida de carga progresiva y vigilada, aunque el restablecimiento de la propulsión siga siendo innegociable — una carga brusca sobre un equipo debilitado puede transformar una avería manejable en una más grave, o incluso en la pérdida total de la fuente de emergencia." },
      { q:"Eres el oficial de máquinas de guardia en el momento del blackout. Piensas que puedes restablecer la situación solo antes de que empeore, y dudas en llamar de inmediato al Jefe de Máquinas. ¿Qué reflejo ERM se aplica aquí?", opts:["Continuar solo, despertar al Jefe de Máquinas por un incidente que crees controlar se vería mal","Alertar de inmediato al Jefe de Máquinas y al puente — un blackout es por naturaleza un evento de recursos compartidos, y la duda en pedir ayuda es precisamente el sesgo que el ERM busca corregir","Esperar a que la situación empeore más para estar seguro de que la llamada está justificada","Resolver primero por completo el problema eléctrico antes de mencionar el incidente a nadie"], correct:1, expl:"El ERM identifica precisamente esta duda jerárquica como un factor de riesgo: un blackout moviliza potencialmente a todo el equipo de máquinas y afecta directamente a la seguridad de la navegación — la alerta inmediata al Jefe de Máquinas y al puente nunca es una opción secundaria." },
      { q:"La alimentación se restablece mediante el generador de emergencia y la propulsión vuelve a estar disponible. La urgencia inmediata parece resuelta. ¿Cuál es la buena práctica en esta etapa?", opts:["Considerar el incidente cerrado y volver a poner en servicio el generador principal sin investigación","Continuar la vigilancia e investigar la causa raíz del disparo antes de volver a la configuración normal — el fin del blackout no significa el fin del riesgo de repetición","Parar el generador de emergencia de inmediato para ahorrar combustible","No registrar el incidente ya que la situación está restablecida"], correct:1, expl:"Como en toda avería crítica, la reevaluación continua sigue siendo indispensable: restablecer la alimentación no sustituye el diagnóstico de la causa raíz, y volver a la configuración normal sin investigación expone a una repetición del mismo incidente." },
    ],
    pt: [
      { q:"Estás de quarto na casa das máquinas numa zona de navegação restrita (canal estreito / tráfego denso). Um gerador principal dispara bruscamente, provocando a perda do quadro principal e, portanto, da propulsão (blackout). Qual é a tua prioridade imediata?", opts:["Esperar que o gerador reinicie sozinho antes de agir","Arrancar de imediato o gerador de emergência para restabelecer a alimentação crítica, informando sem demora a ponte","Diagnosticar primeiro a causa exata do disparo antes de qualquer ação de restabelecimento","Esperar a chegada do Chefe de Máquinas antes de qualquer manobra"], correct:1, expl:"Um blackout numa zona de navegação restrita é uma emergência de dupla dimensão: restabelecer a alimentação crítica (gerador de emergência) é a prioridade imediata, juntamente com informar sem demora a ponte já que o navio está sem propulsão — o diagnóstico completo da causa vem depois da segurança imediata." },
      { q:"O gerador de emergência arranca, mas sabes que recentemente apresentou uma anomalia de arrefecimento não totalmente resolvida. A pressão para restabelecer a propulsão o mais rápido possível é forte. O que deves ter em mente antes de o levar a plena carga de imediato?", opts:["Nada em particular, restabelecer a propulsão prevalece sempre sem reserva","Uma subida de carga demasiado rápida num gerador fragilizado pode provocar uma segunda avaria crítica — a colocação em serviço deve continuar progressiva e vigiada, mesmo sob pressão de tempo","É preciso esvaziar completamente o circuito de arrefecimento antes de qualquer arranque","A anomalia de arrefecimento não tem qualquer relação com a carga aplicada ao gerador"], correct:1, expl:"Um gerador já fragilizado exige uma subida de carga progressiva e vigiada, mesmo que o restabelecimento da propulsão continue a ser inegociável — uma carga brusca sobre um equipamento fragilizado pode transformar uma avaria gerível numa avaria mais grave, ou mesmo na perda total da fonte de emergência." },
      { q:"És o oficial de máquinas de quarto no momento do blackout. Pensas que consegues restabelecer a situação sozinho antes que piore, e hesitas em chamar de imediato o Chefe de Máquinas. Que reflexo ERM se aplica aqui?", opts:["Continuar sozinho, acordar o Chefe de Máquinas por um incidente que pensas conseguir controlar seria mal visto","Alertar de imediato o Chefe de Máquinas e a ponte — um blackout é por natureza um evento de recursos partilhados, e a hesitação em pedir ajuda é precisamente o viés que o ERM procura corrigir","Esperar que a situação piore ainda mais para ter a certeza de que a chamada se justifica","Resolver primeiro por completo o problema elétrico antes de mencionar o incidente a quem quer que seja"], correct:1, expl:"O ERM identifica precisamente esta hesitação hierárquica como um fator de risco: um blackout mobiliza potencialmente toda a equipa de máquinas e afeta diretamente a segurança da navegação — o alerta imediato ao Chefe de Máquinas e à ponte nunca é uma opção secundária." },
      { q:"A alimentação é restabelecida através do gerador de emergência e a propulsão volta a estar disponível. A urgência imediata parece resolvida. Qual é a boa prática nesta fase?", opts:["Considerar o incidente encerrado e voltar a colocar o gerador principal em serviço sem investigação","Continuar a vigilância e investigar a causa raiz do disparo antes de voltar à configuração normal — o fim do blackout não significa o fim do risco de repetição","Parar o gerador de emergência de imediato para poupar combustível","Não registar o incidente já que a situação está restabelecida"], correct:1, expl:"Tal como em qualquer avaria crítica, a reavaliação contínua continua a ser indispensável: restabelecer a alimentação não substitui o diagnóstico da causa raiz, e voltar à configuração normal sem investigação expõe a uma repetição do mesmo incidente." },
    ],
  },

  // ══════════════════════════════════════
  // THEME 2 — Engine room fire & evacuation
  // (Fire response + Firefighting + ERM authority/escalation + Muster reflex)
  // ══════════════════════════════════════
  theme2_engine_room_fire: {
    fr: [
      { q:"Une fuite de combustible s'enflamme au contact d'une surface chaude en salle des machines. L'alarme incendie se déclenche. Quelle est votre priorité immédiate ?", opts:["Rechercher d'abord l'origine exacte de la fuite avant toute action","Donner l'alerte incendie, couper l'alimentation combustible de la zone concernée et engager l'extinction appropriée sans délai","Attendre la confirmation du Commandant avant toute action","Ventiler immédiatement la salle des machines en priorité"], correct:1, expl:"Face à un feu combustible sur surface chaude, la priorité est de couper l'alimentation en combustible de la zone touchée et d'engager l'extinction immédiatement, en parallèle de l'alerte — un feu combustible non contenu se propage très rapidement en salle des machines." },
      { q:"Le feu ne cède pas aux premières mesures d'extinction. Vous hésitez à déclencher la procédure d'évacuation de la salle des machines, pensant que la situation reste maîtrisable seul. Quel réflexe s'applique ?", opts:["Continuer seul les tentatives d'extinction sans en informer davantage l'équipe","Signaler immédiatement l'aggravation et engager, si nécessaire, l'évacuation et le confinement (fermeture ventilation, arrêt combustible général) sans attendre que la situation devienne incontrôlable","Attendre un signe plus net avant d'alerter qui que ce soit","Poursuivre l'extinction jusqu'à épuisement des moyens avant d'envisager l'évacuation"], correct:1, expl:"Un feu qui ne cède pas aux premières mesures doit déclencher sans délai l'escalade vers le confinement et l'évacuation si nécessaire — attendre une aggravation supplémentaire avant d'agir revient à réduire la marge de manœuvre de toute l'équipe." },
      { q:"L'équipe a évacué la salle des machines et le feu semble maîtrisé depuis l'extérieur. Quelle est la bonne pratique immédiate ?", opts:["Considérer l'incident terminé dès que les flammes ne sont plus visibles","Confirmer le comptage complet du personnel, maintenir la surveillance de la zone confinée et ne réintégrer qu'après confirmation que le risque de réinflammation est écarté","Rouvrir immédiatement la ventilation pour évacuer la fumée sans délai","Reprendre le fonctionnement normal des machines dès que possible"], correct:1, expl:"Après un incendie en espace confiné, le comptage du personnel et le maintien de la surveillance sont impératifs avant toute réintégration — un feu apparemment maîtrisé peut se raviver, notamment si le confinement est levé prématurément." },
    ],
    en: [
      { q:"A fuel leak ignites on contact with a hot surface in the engine room. The fire alarm triggers. What is your immediate priority?", opts:["Look for the exact source of the leak first before any action","Raise the fire alarm, cut off the fuel supply to the affected area and initiate appropriate firefighting without delay","Wait for the Captain's confirmation before any action","Ventilate the engine room immediately as a priority"], correct:1, expl:"Facing a fuel fire on a hot surface, the priority is to cut the fuel supply to the affected area and begin firefighting immediately, alongside raising the alarm — an uncontained fuel fire spreads very quickly in the engine room." },
      { q:"The fire does not respond to the initial firefighting measures. You hesitate to trigger the engine room evacuation procedure, thinking the situation is still manageable alone. Which reflex applies?", opts:["Continue alone with extinguishing attempts without informing the team further","Immediately report the worsening situation and, if necessary, initiate evacuation and boundary isolation (closing ventilation, general fuel shutoff) without waiting for the situation to become uncontrollable","Wait for a clearer sign before alerting anyone","Continue firefighting until resources are exhausted before considering evacuation"], correct:1, expl:"A fire that does not respond to initial measures must trigger immediate escalation toward containment and evacuation if necessary — waiting for further worsening before acting reduces the whole team's margin for maneuver." },
      { q:"The team has evacuated the engine room and the fire appears to be under control from outside. What is the correct immediate practice?", opts:["Consider the incident over as soon as flames are no longer visible","Confirm a complete headcount, maintain monitoring of the confined area, and only re-enter once confirmed that the risk of re-ignition is ruled out","Reopen ventilation immediately to clear the smoke without delay","Resume normal machinery operation as soon as possible"], correct:1, expl:"After a fire in a confined space, headcount and continued monitoring are essential before any re-entry — an apparently controlled fire can reignite, especially if containment is lifted prematurely." },
    ],
    es: [
      { q:"Una fuga de combustible se inflama al contacto con una superficie caliente en la sala de máquinas. Se activa la alarma de incendio. ¿Cuál es tu prioridad inmediata?", opts:["Buscar primero el origen exacto de la fuga antes de cualquier acción","Dar la alarma de incendio, cortar la alimentación de combustible de la zona afectada e iniciar la extinción adecuada sin demora","Esperar la confirmación del Capitán antes de cualquier acción","Ventilar de inmediato la sala de máquinas como prioridad"], correct:1, expl:"Ante un fuego de combustible sobre una superficie caliente, la prioridad es cortar la alimentación de combustible de la zona afectada e iniciar la extinción de inmediato, junto con dar la alarma — un fuego de combustible no contenido se propaga muy rápido en la sala de máquinas." },
      { q:"El fuego no cede a las primeras medidas de extinción. Dudas en activar el procedimiento de evacuación, pensando que la situación sigue siendo manejable solo. ¿Qué reflejo se aplica?", opts:["Continuar solo los intentos de extinción sin informar más al equipo","Informar de inmediato del empeoramiento y activar, si es necesario, la evacuación y el confinamiento (cierre de ventilación, corte general de combustible) sin esperar a que la situación se vuelva incontrolable","Esperar una señal más clara antes de alertar a nadie","Continuar la extinción hasta agotar los medios antes de considerar la evacuación"], correct:1, expl:"Un fuego que no cede a las primeras medidas debe desencadenar sin demora la escalada hacia el confinamiento y la evacuación si es necesario — esperar un empeoramiento adicional antes de actuar reduce el margen de maniobra de todo el equipo." },
      { q:"El equipo ha evacuado la sala de máquinas y el fuego parece controlado desde el exterior. ¿Cuál es la buena práctica inmediata?", opts:["Considerar el incidente terminado en cuanto las llamas ya no sean visibles","Confirmar el recuento completo del personal, mantener la vigilancia de la zona confinada y no reingresar hasta confirmar que se descarta el riesgo de reignición","Reabrir de inmediato la ventilación para evacuar el humo sin demora","Reanudar el funcionamiento normal de las máquinas cuanto antes"], correct:1, expl:"Tras un incendio en un espacio confinado, el recuento del personal y el mantenimiento de la vigilancia son imperativos antes de cualquier reingreso — un fuego aparentemente controlado puede reavivarse, especialmente si el confinamiento se levanta prematuramente." },
    ],
    pt: [
      { q:"Uma fuga de combustível incendeia-se ao contacto com uma superfície quente na casa das máquinas. O alarme de incêndio dispara. Qual é a tua prioridade imediata?", opts:["Procurar primeiro a origem exata da fuga antes de qualquer ação","Dar o alarme de incêndio, cortar a alimentação de combustível da zona afetada e iniciar a extinção adequada sem demora","Esperar a confirmação do Comandante antes de qualquer ação","Ventilar de imediato a casa das máquinas como prioridade"], correct:1, expl:"Perante um fogo de combustível sobre uma superfície quente, a prioridade é cortar a alimentação de combustível da zona afetada e iniciar a extinção de imediato, juntamente com o alarme — um fogo de combustível não contido propaga-se muito rapidamente na casa das máquinas." },
      { q:"O fogo não cede às primeiras medidas de extinção. Hesitas em acionar o procedimento de evacuação, pensando que a situação continua controlável sozinho. Que reflexo se aplica?", opts:["Continuar sozinho as tentativas de extinção sem informar mais a equipa","Reportar de imediato o agravamento e acionar, se necessário, a evacuação e o confinamento (fecho da ventilação, corte geral de combustível) sem esperar que a situação se torne incontrolável","Esperar um sinal mais claro antes de alertar quem quer que seja","Continuar a extinção até esgotar os meios antes de considerar a evacuação"], correct:1, expl:"Um fogo que não cede às primeiras medidas deve desencadear sem demora a escalada para o confinamento e a evacuação se necessário — esperar por um agravamento adicional antes de agir reduz a margem de manobra de toda a equipa." },
      { q:"A equipa evacuou a casa das máquinas e o fogo parece controlado a partir do exterior. Qual é a boa prática imediata?", opts:["Considerar o incidente terminado assim que as chamas deixarem de ser visíveis","Confirmar a contagem completa do pessoal, manter a vigilância da zona confinada e só reentrar após confirmação de que o risco de reignição está afastado","Reabrir de imediato a ventilação para evacuar o fumo sem demora","Retomar o funcionamento normal das máquinas assim que possível"], correct:1, expl:"Após um incêndio num espaço confinado, a contagem do pessoal e a manutenção da vigilância são imperativas antes de qualquer reentrada — um fogo aparentemente controlado pode reacender-se, especialmente se o confinamento for levantado prematuramente." },
    ],
  },

  // ══════════════════════════════════════
  // THEME 3 — Environmental incident under operational pressure (MARPOL)
  // (MARPOL Annex I + Purifiers/OWS + Safety culture)
  // ══════════════════════════════════════
  theme3_marpol_pressure: {
    fr: [
      { q:"Le séparateur d'eaux de cale (OWS) affiche une alarme de dépassement du seuil de 15 ppm alors que le navire doit appareiller sous peu et que les cales sont pleines. Quelle est l'action correcte ?", opts:["Contourner temporairement l'OWS pour évacuer les eaux de cale avant le départ","Ne pas rejeter les eaux de cale non conformes ; stocker ou faire traiter à terre si nécessaire, et informer le commandement du retard potentiel","Rejeter quand même en réduisant légèrement le débit pour rester discret","Attendre le départ pour rejeter en haute mer sans traitement"], correct:1, expl:"Aucune pression opérationnelle ne justifie un rejet non conforme au seuil des 15 ppm (Annexe I) ni un contournement de l'OWS — les eaux non conformes doivent être stockées ou déchargées à terre, quitte à en informer le commandement pour ajuster le planning." },
      { q:"Le Chef Mécanicien vous suggère d'inscrire dans le registre des hydrocarbures une opération légèrement différente de ce qui s'est réellement passé, pour éviter des questions du port. Quelle est l'attitude correcte ?", opts:["S'exécuter, c'est une pratique mineure et sans conséquence","Refuser et consigner les opérations réelles — le registre des hydrocarbures doit refléter exactement les opérations effectuées, sans exception","Accepter uniquement si le Commandant est également d'accord","Modifier l'inscription seulement si aucun contrôle n'est prévu à l'escale suivante"], correct:1, expl:"Le registre des hydrocarbures est un document légal qui doit refléter fidèlement chaque opération réelle — aucune pression hiérarchique ou opérationnelle ne justifie une inscription inexacte, quelles que soient les conséquences perçues comme mineures." },
      { q:"Une non-conformité environnementale mineure a tout de même eu lieu de façon non intentionnelle (petit rejet accidentel). Quelle est la bonne pratique immédiate ?", opts:["Ne rien signaler puisque l'incident est mineur et non intentionnel","Signaler immédiatement l'incident selon la procédure interne et le consigner, indépendamment de son caractère mineur ou accidentel","Attendre de voir si quelqu'un le remarque avant d'agir","Corriger discrètement la situation sans qu'aucune trace n'en soit gardée"], correct:1, expl:"Tout incident environnemental, même mineur et non intentionnel, doit être signalé et consigné sans délai — la transparence et la traçabilité priment sur la minimisation de l'incident, et dissimuler expose à des conséquences bien plus graves qu'un signalement rapide." },
    ],
    en: [
      { q:"The Oily Water Separator (OWS) shows an alarm exceeding the 15 ppm threshold while the vessel is due to depart shortly and the bilge tanks are full. What is the correct action?", opts:["Temporarily bypass the OWS to discharge the bilge water before departure","Do not discharge non-compliant bilge water; store it or arrange shore reception if necessary, and inform command of the potential delay","Discharge anyway while slightly reducing the flow rate to stay discreet","Wait for departure to discharge on the high seas without treatment"], correct:1, expl:"No operational pressure justifies a discharge that fails the 15 ppm threshold (Annex I) or bypassing the OWS — non-compliant water must be stored or discharged ashore, even if it means informing command to adjust the schedule." },
      { q:"The Chief Engineer suggests logging a slightly different operation than what actually happened in the Oil Record Book, to avoid questions from the port. What is the correct attitude?", opts:["Comply, it's a minor practice without consequence","Refuse and log the actual operations — the Oil Record Book must exactly reflect the operations carried out, without exception","Accept only if the Captain also agrees","Alter the entry only if no inspection is expected at the next port"], correct:1, expl:"The Oil Record Book is a legal document that must faithfully reflect every actual operation — no hierarchical or operational pressure justifies an inaccurate entry, regardless of how minor the consequences may seem." },
      { q:"A minor environmental non-compliance nonetheless occurred unintentionally (a small accidental discharge). What is the correct immediate practice?", opts:["Report nothing since the incident is minor and unintentional","Immediately report the incident according to internal procedure and log it, regardless of how minor or accidental it was","Wait to see if anyone notices before acting","Discreetly fix the situation without keeping any record"], correct:1, expl:"Any environmental incident, however minor and unintentional, must be reported and logged without delay — transparency and traceability take priority over minimizing the incident, and concealment exposes to far more serious consequences than a prompt report." },
    ],
    es: [
      { q:"El separador de aguas de sentina (OWS) muestra una alarma de superación del umbral de 15 ppm mientras el buque debe zarpar en breve y las sentinas están llenas. ¿Cuál es la acción correcta?", opts:["Puentear temporalmente el OWS para evacuar las aguas de sentina antes de zarpar","No verter las aguas de sentina no conformes; almacenarlas o hacerlas tratar en tierra si es necesario, e informar al mando del posible retraso","Verter de todos modos reduciendo ligeramente el caudal para pasar desapercibido","Esperar a zarpar para verter en alta mar sin tratamiento"], correct:1, expl:"Ninguna presión operativa justifica un vertido no conforme con el umbral de 15 ppm (Anexo I) ni un puenteo del OWS — las aguas no conformes deben almacenarse o descargarse en tierra, aunque ello implique informar al mando para ajustar el plan." },
      { q:"El Jefe de Máquinas te sugiere anotar en el Libro de Registro de Hidrocarburos una operación ligeramente distinta de lo que realmente ocurrió, para evitar preguntas del puerto. ¿Cuál es la actitud correcta?", opts:["Obedecer, es una práctica menor y sin consecuencias","Negarse y registrar las operaciones reales — el Libro de Registro de Hidrocarburos debe reflejar exactamente las operaciones realizadas, sin excepción","Aceptar solo si el Capitán también está de acuerdo","Modificar la anotación solo si no se prevé ninguna inspección en la siguiente escala"], correct:1, expl:"El Libro de Registro de Hidrocarburos es un documento legal que debe reflejar fielmente cada operación real — ninguna presión jerárquica u operativa justifica una anotación inexacta, por menores que parezcan las consecuencias." },
      { q:"Se produjo, sin embargo, una no conformidad ambiental menor de forma no intencionada (un pequeño vertido accidental). ¿Cuál es la buena práctica inmediata?", opts:["No informar ya que el incidente es menor y no intencionado","Informar de inmediato del incidente según el procedimiento interno y registrarlo, independientemente de su carácter menor o accidental","Esperar a ver si alguien lo nota antes de actuar","Corregir discretamente la situación sin dejar ningún rastro"], correct:1, expl:"Todo incidente ambiental, por menor y no intencionado que sea, debe informarse y registrarse sin demora — la transparencia y la trazabilidad priman sobre minimizar el incidente, y ocultarlo expone a consecuencias mucho más graves que un informe rápido." },
    ],
    pt: [
      { q:"O separador de águas de porão (OWS) mostra um alarme de ultrapassagem do limiar de 15 ppm enquanto o navio deve zarpar em breve e os porões estão cheios. Qual é a ação correta?", opts:["Contornar temporariamente o OWS para escoar as águas de porão antes de zarpar","Não descarregar as águas de porão não conformes; armazená-las ou fazê-las tratar em terra se necessário, e informar o comando do possível atraso","Descarregar mesmo assim reduzindo ligeiramente o caudal para passar despercebido","Esperar pela partida para descarregar em alto mar sem tratamento"], correct:1, expl:"Nenhuma pressão operacional justifica uma descarga não conforme com o limiar de 15 ppm (Anexo I) nem contornar o OWS — as águas não conformes devem ser armazenadas ou descarregadas em terra, mesmo que isso implique informar o comando para ajustar o plano." },
      { q:"O Chefe de Máquinas sugere-te registar no Livro de Registo de Hidrocarbonetos uma operação ligeiramente diferente do que realmente aconteceu, para evitar perguntas do porto. Qual é a atitude correta?", opts:["Obedecer, é uma prática menor e sem consequências","Recusar e registar as operações reais — o Livro de Registo de Hidrocarbonetos deve refletir exatamente as operações realizadas, sem exceção","Aceitar apenas se o Comandante também concordar","Alterar o registo apenas se não estiver prevista nenhuma inspeção na próxima escala"], correct:1, expl:"O Livro de Registo de Hidrocarbonetos é um documento legal que deve refletir fielmente cada operação real — nenhuma pressão hierárquica ou operacional justifica um registo inexato, por menores que pareçam as consequências." },
      { q:"Ocorreu, no entanto, uma não conformidade ambiental menor de forma não intencional (uma pequena descarga acidental). Qual é a boa prática imediata?", opts:["Não reportar já que o incidente é menor e não intencional","Reportar de imediato o incidente segundo o procedimento interno e registá-lo, independentemente do seu carácter menor ou acidental","Esperar para ver se alguém repara antes de agir","Corrigir discretamente a situação sem manter qualquer registo"], correct:1, expl:"Todo incidente ambiental, por menor e não intencional que seja, deve ser reportado e registado sem demora — a transparência e a rastreabilidade prevalecem sobre minimizar o incidente, e ocultá-lo expõe a consequências muito mais graves do que um relato rápido." },
    ],
  },

  // ══════════════════════════════════════
  // THEME 4 — Medical emergency in machinery spaces
  // (First Aid + ERM coordination + MEDEVAC communication)
  // ══════════════════════════════════════
  theme4_medical_engine_space: {
    fr: [
      { q:"Un membre de l'équipe machine est gravement brûlé près d'une conduite de vapeur haute pression. Quelle est votre priorité immédiate ?", opts:["Continuer la manœuvre en cours avant de s'occuper du blessé","Sécuriser la zone (isoler la source si possible sans danger), prodiguer les premiers secours immédiats et alerter sans délai pour une évacuation médicale","Attendre l'arrivée du responsable sécurité avant tout geste","Déplacer immédiatement le blessé sans évaluation préalable de la zone"], correct:1, expl:"Face à une brûlure grave à proximité d'un danger actif, la priorité est de sécuriser la zone sans s'exposer inutilement, prodiguer les premiers secours immédiats, et alerter sans délai — le geste réflexe de déplacer un blessé sans évaluation peut aggraver la blessure." },
      { q:"Le blessé doit être évacué de la salle des machines vers le pont pour une évacuation médicale, mais l'opération en cours nécessite une présence continue en salle des machines. Comment concilier les deux exigences ?", opts:["Abandonner totalement la surveillance machine pour se consacrer uniquement à l'évacuation","Répartir les rôles immédiatement au sein de l'équipe machine — premiers secours et évacuation d'un côté, maintien minimal de la surveillance critique de l'autre — sans laisser l'un des deux impératifs sans réponse","Prioriser uniquement l'opération machine et différer les secours","Attendre que l'opération machine soit terminée avant de s'occuper du blessé"], correct:1, expl:"Une urgence médicale et une exigence opérationnelle ne s'excluent pas : la coordination ERM consiste à répartir les rôles dans l'équipe disponible pour répondre aux deux impératifs, plutôt que de sacrifier entièrement l'un pour l'autre." },
      { q:"La passerelle doit être informée pour coordonner une évacuation médicale (MEDEVAC). Quelle information est essentielle à transmettre sans délai ?", opts:["Uniquement le nom du blessé, le reste peut attendre","L'état du blessé, la nature de la blessure, et la nécessité d'une assistance médicale externe, pour permettre une coordination rapide avec les secours extérieurs","Aucune information n'est nécessaire tant que le blessé n'est pas stabilisé","Uniquement la position du navire, sans détail médical"], correct:1, expl:"Une coordination MEDEVAC efficace exige une transmission rapide et complète de l'état du blessé et de la nature de la blessure, pour permettre à la passerelle et aux secours extérieurs d'organiser la réponse la plus adaptée sans délai supplémentaire." },
    ],
    en: [
      { q:"A member of the engine team is severely burned near a high-pressure steam pipe. What is your immediate priority?", opts:["Continue the ongoing operation before attending to the injured person","Secure the area (isolate the source if it can be done safely), provide immediate first aid, and alert without delay for a medical evacuation","Wait for the safety officer to arrive before any action","Immediately move the injured person without first assessing the area"], correct:1, expl:"Facing a severe burn near an active hazard, the priority is to secure the area without unnecessary exposure, provide immediate first aid, and alert without delay — moving an injured person reflexively without assessment can worsen the injury." },
      { q:"The injured person must be evacuated from the engine room to the deck for a medical evacuation, but the ongoing operation requires continuous presence in the engine room. How do you reconcile both requirements?", opts:["Fully abandon machinery monitoring to focus solely on the evacuation","Immediately split roles within the available engine team — first aid and evacuation on one side, minimal maintenance of critical monitoring on the other — without leaving either requirement unanswered","Prioritize only the machinery operation and defer first aid","Wait until the machinery operation is finished before attending to the injured person"], correct:1, expl:"A medical emergency and an operational requirement are not mutually exclusive: ERM coordination means splitting roles within the available team to answer both needs, rather than fully sacrificing one for the other." },
      { q:"The bridge must be informed to coordinate a medical evacuation (MEDEVAC). What information is essential to transmit without delay?", opts:["Only the injured person's name, the rest can wait","The injured person's condition, the nature of the injury, and the need for external medical assistance, to enable rapid coordination with outside responders","No information is necessary until the injured person is stabilized","Only the vessel's position, without medical detail"], correct:1, expl:"Effective MEDEVAC coordination requires a rapid and complete transmission of the injured person's condition and the nature of the injury, so the bridge and outside responders can organize the most appropriate response without further delay." },
    ],
    es: [
      { q:"Un miembro del equipo de máquinas sufre quemaduras graves cerca de una tubería de vapor de alta presión. ¿Cuál es tu prioridad inmediata?", opts:["Continuar la maniobra en curso antes de atender al herido","Asegurar la zona (aislar la fuente si es posible sin peligro), prestar los primeros auxilios inmediatos y alertar sin demora para una evacuación médica","Esperar la llegada del responsable de seguridad antes de cualquier gesto","Desplazar de inmediato al herido sin evaluar antes la zona"], correct:1, expl:"Ante una quemadura grave cerca de un peligro activo, la prioridad es asegurar la zona sin exponerse innecesariamente, prestar los primeros auxilios inmediatos y alertar sin demora — el gesto reflejo de mover a un herido sin evaluación puede agravar la lesión." },
      { q:"El herido debe ser evacuado de la sala de máquinas a cubierta para una evacuación médica, pero la operación en curso requiere una presencia continua en la sala de máquinas. ¿Cómo conciliar ambas exigencias?", opts:["Abandonar totalmente la vigilancia de las máquinas para dedicarse solo a la evacuación","Repartir los roles de inmediato dentro del equipo de máquinas disponible — primeros auxilios y evacuación por un lado, mantenimiento mínimo de la vigilancia crítica por otro — sin dejar ninguna de las dos exigencias sin respuesta","Priorizar únicamente la operación de máquinas y aplazar los auxilios","Esperar a que termine la operación de máquinas antes de atender al herido"], correct:1, expl:"Una urgencia médica y una exigencia operativa no se excluyen entre sí: la coordinación ERM consiste en repartir los roles dentro del equipo disponible para responder a ambas exigencias, en lugar de sacrificar por completo una por la otra." },
      { q:"El puente debe ser informado para coordinar una evacuación médica (MEDEVAC). ¿Qué información es esencial transmitir sin demora?", opts:["Únicamente el nombre del herido, el resto puede esperar","El estado del herido, la naturaleza de la lesión y la necesidad de asistencia médica externa, para permitir una coordinación rápida con los servicios de socorro exteriores","Ninguna información es necesaria mientras el herido no esté estabilizado","Únicamente la posición del buque, sin detalle médico"], correct:1, expl:"Una coordinación MEDEVAC eficaz exige una transmisión rápida y completa del estado del herido y la naturaleza de la lesión, para permitir al puente y a los servicios exteriores organizar la respuesta más adecuada sin demora adicional." },
    ],
    pt: [
      { q:"Um membro da equipa de máquinas sofre queimaduras graves perto de uma tubagem de vapor de alta pressão. Qual é a tua prioridade imediata?", opts:["Continuar a manobra em curso antes de atender o ferido","Assegurar a zona (isolar a fonte se possível sem perigo), prestar os primeiros socorros imediatos e alertar sem demora para uma evacuação médica","Esperar a chegada do responsável de segurança antes de qualquer gesto","Deslocar de imediato o ferido sem avaliar antes a zona"], correct:1, expl:"Perante uma queimadura grave perto de um perigo ativo, a prioridade é assegurar a zona sem se expor desnecessariamente, prestar os primeiros socorros imediatos e alertar sem demora — o gesto reflexo de mover um ferido sem avaliação pode agravar a lesão." },
      { q:"O ferido deve ser evacuado da casa das máquinas para o convés para uma evacuação médica, mas a operação em curso exige uma presença contínua na casa das máquinas. Como conciliar as duas exigências?", opts:["Abandonar totalmente a vigilância das máquinas para se dedicar apenas à evacuação","Repartir de imediato os papéis dentro da equipa de máquinas disponível — primeiros socorros e evacuação de um lado, manutenção mínima da vigilância crítica do outro — sem deixar nenhuma das duas exigências sem resposta","Priorizar apenas a operação de máquinas e adiar os socorros","Esperar que a operação de máquinas termine antes de atender o ferido"], correct:1, expl:"Uma urgência médica e uma exigência operacional não se excluem mutuamente: a coordenação ERM consiste em repartir os papéis dentro da equipa disponível para responder às duas exigências, em vez de sacrificar totalmente uma pela outra." },
      { q:"A ponte deve ser informada para coordenar uma evacuação médica (MEDEVAC). Que informação é essencial transmitir sem demora?", opts:["Apenas o nome do ferido, o resto pode esperar","O estado do ferido, a natureza da lesão e a necessidade de assistência médica externa, para permitir uma coordenação rápida com os socorros exteriores","Nenhuma informação é necessária enquanto o ferido não estiver estabilizado","Apenas a posição do navio, sem detalhe médico"], correct:1, expl:"Uma coordenação MEDEVAC eficaz exige uma transmissão rápida e completa do estado do ferido e da natureza da lesão, para permitir à ponte e aos socorros exteriores organizar a resposta mais adequada sem demora adicional." },
    ],
  },

  // ══════════════════════════════════════
  // THEME 5 — Abandon ship / dead ship from the engine room
  // (Lifeboats/HRU + ERM leadership + Machinery securing + Muster headcount)
  // ══════════════════════════════════════
  theme5_abandon_ship_engine: {
    fr: [
      { q:"L'ordre d'abandon du navire est donné suite à une avarie majeure incontrôlable. Vous êtes en salle des machines. Quelle est votre priorité immédiate avant de rejoindre le poste de rassemblement ?", opts:["Quitter immédiatement la salle des machines sans autre action","Exécuter rapidement les actions de sécurisation prioritaires de la machine (arrêt sécurisé, isolement combustible si le temps le permet) puis rejoindre sans délai le poste de rassemblement","Rester en salle des machines tant que les moteurs tournent encore","Attendre les instructions détaillées du Chef Mécanicien avant tout geste"], correct:1, expl:"Un ordre d'abandon prime sur toute autre considération, mais les gestes de sécurisation rapide de la machine, s'ils sont réalisables dans le temps disponible sans mettre en danger l'équipe, réduisent le risque pour l'environnement ou pour d'éventuelles personnes restées à bord — sans jamais retarder indûment l'évacuation elle-même." },
      { q:"Un membre de l'équipe machine insiste pour tenter une réparation de dernière minute qui pourrait, selon lui, éviter l'abandon. Quelle est l'attitude correcte une fois l'ordre d'abandon donné ?", opts:["Le laisser tenter la réparation, cela pourrait sauver le navire","Refuser toute tentative non planifiée une fois l'ordre donné — l'ordre d'abandon prime sur toute initiative individuelle, aussi bien intentionnée soit-elle","Le laisser faire à condition qu'il fasse vite","Demander l'avis du reste de l'équipe avant de trancher"], correct:1, expl:"Une fois l'ordre d'abandon donné, aucune initiative individuelle de réparation ne doit primer sur la procédure — ce type d'initiative isolée, même bien intentionnée, a par le passé coûté des vies en retardant l'évacuation d'une ou plusieurs personnes." },
      { q:"Avant de quitter définitivement la salle des machines, quelle communication est essentielle ?", opts:["Aucune, il faut sortir au plus vite sans perdre de temps à communiquer","Confirmer à la passerelle que la salle des machines est évacuée et l'état dans lequel elle a été laissée (machines arrêtées ou non, risques résiduels), pour que cette information intègre le comptage général et la coordination de l'abandon","Communiquer uniquement une fois au poste de rassemblement","Laisser un message écrit sur place pour les secours"], correct:1, expl:"La confirmation à la passerelle que la salle des machines est évacuée, avec l'état dans lequel elle a été laissée, est une information essentielle à la coordination générale de l'abandon — elle doit être transmise avant de quitter définitivement la zone, pas après." },
      { q:"Au poste de rassemblement, vous réalisez qu'un collègue de la salle des machines n'a pas encore été comptabilisé. Quelle est la bonne pratique ?", opts:["Attendre l'embarquement dans les embarcations, il finira bien par arriver","Signaler immédiatement l'absence au responsable du poste de rassemblement pour déclencher une vérification, sans attendre le dernier moment pour agir","Retourner seul en salle des machines pour le chercher","Ne rien dire pour ne pas retarder l'embarquement des autres"], correct:1, expl:"Toute absence constatée au poste de rassemblement doit être signalée immédiatement au responsable, qui coordonnera la vérification selon la procédure — ni l'attente passive ni une initiative individuelle non coordonnée pour retourner chercher la personne ne sont des réponses sûres." },
    ],
    en: [
      { q:"The order to abandon ship is given following an uncontrollable major casualty. You are in the engine room. What is your immediate priority before joining the muster station?", opts:["Leave the engine room immediately without any further action","Quickly carry out priority machinery securing actions (safe shutdown, fuel isolation if time allows) then join the muster station without delay","Stay in the engine room as long as the engines are still running","Wait for detailed instructions from the Chief Engineer before any action"], correct:1, expl:"An abandon-ship order overrides every other consideration, but quick machinery-securing actions, if achievable within the available time without endangering the team, reduce the risk to the environment or to anyone who might remain aboard — without ever unduly delaying the evacuation itself." },
      { q:"A member of the engine team insists on attempting a last-minute repair that, in their view, could avoid the need to abandon ship. What is the correct attitude once the abandon-ship order has been given?", opts:["Let them attempt the repair, it might save the vessel","Refuse any unplanned attempt once the order has been given — the abandon-ship order takes priority over any individual initiative, however well-intentioned","Allow it as long as they are quick about it","Ask the rest of the team for their opinion before deciding"], correct:1, expl:"Once the abandon-ship order has been given, no individual repair initiative should take priority over the procedure — this kind of isolated initiative, however well-intentioned, has in the past cost lives by delaying the evacuation of one or more people." },
      { q:"Before permanently leaving the engine room, what communication is essential?", opts:["None, you need to get out as fast as possible without wasting time communicating","Confirm to the bridge that the engine room has been evacuated and the condition it was left in (machinery stopped or not, residual risks), so this information is included in the overall headcount and abandon-ship coordination","Only communicate once at the muster station","Leave a written note on site for rescuers"], correct:1, expl:"Confirming to the bridge that the engine room has been evacuated, along with the condition it was left in, is essential information for the overall coordination of the abandonment — it must be transmitted before permanently leaving the area, not after." },
      { q:"At the muster station, you realize a colleague from the engine room has not yet been accounted for. What is the correct practice?", opts:["Wait until boarding the lifeboats, they'll turn up eventually","Immediately report the absence to the muster station officer in charge to trigger a check, rather than waiting until the last moment to act","Go back alone into the engine room to look for them","Say nothing so as not to delay the boarding of others"], correct:1, expl:"Any absence noted at the muster station must be reported immediately to the officer in charge, who will coordinate the check according to procedure — neither passively waiting nor an uncoordinated individual initiative to go back for the person are safe responses." },
    ],
    es: [
      { q:"Se da la orden de abandono del buque tras una avería mayor incontrolable. Estás en la sala de máquinas. ¿Cuál es tu prioridad inmediata antes de dirigirte al puesto de reunión?", opts:["Salir de inmediato de la sala de máquinas sin ninguna otra acción","Ejecutar rápidamente las acciones prioritarias de aseguramiento de la máquina (parada segura, aislamiento de combustible si el tiempo lo permite) y luego dirigirte sin demora al puesto de reunión","Permanecer en la sala de máquinas mientras los motores sigan funcionando","Esperar instrucciones detalladas del Jefe de Máquinas antes de cualquier gesto"], correct:1, expl:"Una orden de abandono prevalece sobre cualquier otra consideración, pero los gestos rápidos de aseguramiento de la máquina, si son realizables en el tiempo disponible sin poner en peligro al equipo, reducen el riesgo para el medio ambiente o para posibles personas que permanezcan a bordo — sin retrasar nunca indebidamente la evacuación en sí." },
      { q:"Un miembro del equipo de máquinas insiste en intentar una reparación de última hora que, según él, podría evitar el abandono. ¿Cuál es la actitud correcta una vez dada la orden de abandono?", opts:["Dejarle intentar la reparación, podría salvar el buque","Negarse a cualquier intento no planificado una vez dada la orden — la orden de abandono prevalece sobre cualquier iniciativa individual, por bien intencionada que sea","Dejarle hacerlo a condición de que sea rápido","Pedir la opinión del resto del equipo antes de decidir"], correct:1, expl:"Una vez dada la orden de abandono, ninguna iniciativa individual de reparación debe prevalecer sobre el procedimiento — este tipo de iniciativa aislada, por bien intencionada que sea, ha costado vidas en el pasado al retrasar la evacuación de una o varias personas." },
      { q:"Antes de abandonar definitivamente la sala de máquinas, ¿qué comunicación es esencial?", opts:["Ninguna, hay que salir cuanto antes sin perder tiempo comunicando","Confirmar al puente que la sala de máquinas ha sido evacuada y el estado en que ha quedado (máquinas paradas o no, riesgos residuales), para que esta información se integre en el recuento general y la coordinación del abandono","Comunicar únicamente una vez en el puesto de reunión","Dejar un mensaje escrito en el lugar para los equipos de rescate"], correct:1, expl:"Confirmar al puente que la sala de máquinas ha sido evacuada, junto con el estado en que ha quedado, es una información esencial para la coordinación general del abandono — debe transmitirse antes de abandonar definitivamente la zona, no después." },
      { q:"En el puesto de reunión, te das cuenta de que un compañero de la sala de máquinas aún no ha sido contabilizado. ¿Cuál es la buena práctica?", opts:["Esperar al embarque en las embarcaciones, ya aparecerá","Informar de inmediato de la ausencia al responsable del puesto de reunión para activar una verificación, sin esperar al último momento para actuar","Volver solo a la sala de máquinas para buscarlo","No decir nada para no retrasar el embarque de los demás"], correct:1, expl:"Toda ausencia detectada en el puesto de reunión debe informarse de inmediato al responsable, quien coordinará la verificación según el procedimiento — ni la espera pasiva ni una iniciativa individual no coordinada para volver a buscar a la persona son respuestas seguras." },
    ],
    pt: [
      { q:"É dada a ordem de abandono do navio na sequência de uma avaria grave incontrolável. Estás na casa das máquinas. Qual é a tua prioridade imediata antes de te dirigires ao posto de reunião?", opts:["Sair de imediato da casa das máquinas sem qualquer outra ação","Executar rapidamente as ações prioritárias de segurança da máquina (paragem segura, isolamento de combustível se o tempo permitir) e depois dirigir-te sem demora ao posto de reunião","Permanecer na casa das máquinas enquanto os motores ainda estiverem a funcionar","Esperar instruções detalhadas do Chefe de Máquinas antes de qualquer gesto"], correct:1, expl:"Uma ordem de abandono prevalece sobre qualquer outra consideração, mas os gestos rápidos de segurança da máquina, se forem realizáveis no tempo disponível sem colocar a equipa em perigo, reduzem o risco para o ambiente ou para eventuais pessoas que permaneçam a bordo — sem nunca atrasar indevidamente a própria evacuação." },
      { q:"Um membro da equipa de máquinas insiste em tentar uma reparação de última hora que, segundo ele, poderia evitar o abandono. Qual é a atitude correta uma vez dada a ordem de abandono?", opts:["Deixá-lo tentar a reparação, poderia salvar o navio","Recusar qualquer tentativa não planeada uma vez dada a ordem — a ordem de abandono prevalece sobre qualquer iniciativa individual, por bem-intencionada que seja","Deixá-lo fazer desde que seja rápido","Pedir a opinião do resto da equipa antes de decidir"], correct:1, expl:"Uma vez dada a ordem de abandono, nenhuma iniciativa individual de reparação deve prevalecer sobre o procedimento — este tipo de iniciativa isolada, por bem-intencionada que seja, já custou vidas no passado ao atrasar a evacuação de uma ou várias pessoas." },
      { q:"Antes de abandonar definitivamente a casa das máquinas, que comunicação é essencial?", opts:["Nenhuma, é preciso sair o mais rápido possível sem perder tempo a comunicar","Confirmar à ponte que a casa das máquinas foi evacuada e o estado em que ficou (máquinas paradas ou não, riscos residuais), para que esta informação seja integrada na contagem geral e na coordenação do abandono","Comunicar apenas uma vez no posto de reunião","Deixar uma mensagem escrita no local para os socorristas"], correct:1, expl:"Confirmar à ponte que a casa das máquinas foi evacuada, juntamente com o estado em que ficou, é uma informação essencial para a coordenação geral do abandono — deve ser transmitida antes de abandonar definitivamente a zona, não depois." },
      { q:"No posto de reunião, apercebes-te de que um colega da casa das máquinas ainda não foi contabilizado. Qual é a boa prática?", opts:["Esperar pelo embarque nas embarcações, ele há de aparecer","Reportar de imediato a ausência ao responsável do posto de reunião para acionar uma verificação, sem esperar pelo último momento para agir","Voltar sozinho à casa das máquinas para o procurar","Não dizer nada para não atrasar o embarque dos outros"], correct:1, expl:"Toda ausência constatada no posto de reunião deve ser reportada de imediato ao responsável, que coordenará a verificação segundo o procedimento — nem a espera passiva nem uma iniciativa individual não coordenada para voltar a procurar a pessoa são respostas seguras." },
    ],
  },

  // ══════════════════════════════════════
  // THEME 6 — UMS alarm response during unattended watch
  // (Automation/UMS + ERM isolation reflex + multi-alarm prioritization)
  // ══════════════════════════════════════
  theme6_ums_alarm_response: {
    fr: [
      { q:"Vous êtes l'officier machine de garde en configuration UMS (salle des machines sans surveillance). Une alarme critique se déclenche au milieu de la nuit alors que vous n'êtes pas physiquement en salle des machines. Quelle est votre priorité immédiate ?", opts:["Attendre une seconde alarme pour confirmer avant de se déplacer","Se rendre sans délai en salle des machines pour évaluer et traiter l'alarme, dans le respect du délai réglementaire de réponse UMS","Contacter d'abord le Chef Mécanicien avant tout déplacement","Réarmer l'alarme à distance sans vérification physique"], correct:1, expl:"Une alarme critique en configuration UMS impose une réponse physique sans délai, dans le respect du temps de réponse réglementaire — réarmer sans vérification ou attendre une confirmation supplémentaire expose à laisser une situation dangereuse évoluer sans surveillance." },
      { q:"En arrivant, vous constatez que plusieurs alarmes secondaires se sont également déclenchées en cascade, en plus de l'alarme initiale. Vous ne pouvez pas tout traiter simultanément seul. Comment procéder ?", opts:["Traiter les alarmes dans l'ordre chronologique de déclenchement, sans distinction","Identifier et traiter en priorité l'alarme représentant le risque le plus critique pour la sécurité du navire ou des personnes, les alarmes secondaires étant souvent des conséquences de la première","Réarmer toutes les alarmes secondaires pour se concentrer sur la première","Attendre du renfort avant de traiter quoi que ce soit"], correct:1, expl:"Une cascade d'alarmes est souvent la conséquence d'un seul événement racine — la priorisation doit cibler le risque le plus critique en premier, les alarmes secondaires pouvant se résorber une fois la cause principale traitée." },
      { q:"Le délai réglementaire de réponse UMS approche et vous n'avez pas encore pu résoudre ni pleinement diagnostiquer la situation seul. Quelle est la bonne pratique ?", opts:["Continuer seul indéfiniment, demander de l'aide serait un aveu d'échec","Alerter le Chef Mécanicien et la passerelle de la situation en cours, même non résolue, pour ne pas rester seul face à une incertitude prolongée","Attendre que le délai soit largement dépassé avant d'envisager d'alerter","Considérer que l'absence de nouvelle alarme signifie que la situation est résolue"], correct:1, expl:"Une situation non résolue à l'approche du délai réglementaire doit être signalée sans attendre, exactement comme le principe ERM déjà appliqué ailleurs : l'isolement face à une incertitude prolongée est un facteur de risque, pas une preuve de compétence." },
    ],
    en: [
      { q:"You are the duty engineer in UMS configuration (unattended machinery space). A critical alarm triggers in the middle of the night while you are not physically in the engine room. What is your immediate priority?", opts:["Wait for a second alarm to confirm before moving","Go to the engine room without delay to assess and address the alarm, within the required UMS response time","Contact the Chief Engineer first before any move","Reset the alarm remotely without physical verification"], correct:1, expl:"A critical alarm in UMS configuration requires an immediate physical response, within the required response time — resetting without verification or waiting for further confirmation risks letting a dangerous situation develop unmonitored." },
      { q:"Upon arrival, you find that several secondary alarms have also triggered in a cascade, in addition to the initial alarm. You cannot address everything simultaneously alone. How do you proceed?", opts:["Address the alarms in chronological order of triggering, without distinction","Identify and address first the alarm representing the most critical risk to the safety of the vessel or personnel, as secondary alarms are often consequences of the first","Reset all secondary alarms to focus on the first one","Wait for backup before addressing anything"], correct:1, expl:"A cascade of alarms is often the consequence of a single root event — prioritization must target the most critical risk first, as secondary alarms may resolve once the root cause is addressed, rather than handling them indiscriminately in order of arrival." },
      { q:"The required UMS response time is approaching and you have not yet been able to resolve or fully diagnose the situation alone. What is the correct practice?", opts:["Continue alone indefinitely, asking for help would be an admission of failure","Alert the Chief Engineer and the bridge of the ongoing situation, even if unresolved, so as not to remain alone facing prolonged uncertainty","Wait until the time limit is well exceeded before considering an alert","Assume that the absence of a new alarm means the situation is resolved"], correct:1, expl:"An unresolved situation as the required response time approaches must be reported without waiting, exactly as the ERM principle already applied elsewhere: isolation in the face of prolonged uncertainty is a risk factor, not proof of competence." },
    ],
    es: [
      { q:"Eres el oficial de máquinas de guardia en configuración UMS (sala de máquinas sin vigilancia). Se activa una alarma crítica en plena noche mientras no te encuentras físicamente en la sala de máquinas. ¿Cuál es tu prioridad inmediata?", opts:["Esperar una segunda alarma para confirmar antes de desplazarte","Dirigirte sin demora a la sala de máquinas para evaluar y atender la alarma, respetando el plazo de respuesta reglamentario UMS","Contactar primero con el Jefe de Máquinas antes de cualquier desplazamiento","Rearmar la alarma a distancia sin verificación física"], correct:1, expl:"Una alarma crítica en configuración UMS impone una respuesta física sin demora, respetando el tiempo de respuesta reglamentario — rearmar sin verificación o esperar una confirmación adicional expone a dejar evolucionar sin vigilancia una situación peligrosa." },
      { q:"Al llegar, constatas que varias alarmas secundarias también se han activado en cascada, además de la alarma inicial. No puedes atenderlo todo simultáneamente solo. ¿Cómo proceder?", opts:["Atender las alarmas por orden cronológico de activación, sin distinción","Identificar y atender primero la alarma que representa el riesgo más crítico para la seguridad del buque o de las personas, ya que las alarmas secundarias suelen ser consecuencia de la primera","Rearmar todas las alarmas secundarias para concentrarte en la primera","Esperar refuerzos antes de atender cualquier cosa"], correct:1, expl:"Una cascada de alarmas suele ser consecuencia de un único evento raíz — la priorización debe apuntar primero al riesgo más crítico, ya que las alarmas secundarias pueden resolverse una vez tratada la causa principal, en lugar de atenderlas sin criterio por orden de llegada." },
      { q:"El plazo de respuesta reglamentario UMS se acerca y aún no has podido resolver ni diagnosticar completamente la situación solo. ¿Cuál es la buena práctica?", opts:["Continuar solo indefinidamente, pedir ayuda sería una admisión de fracaso","Alertar al Jefe de Máquinas y al puente de la situación en curso, aunque no esté resuelta, para no quedarte solo ante una incertidumbre prolongada","Esperar a que el plazo esté ampliamente superado antes de plantearte alertar","Considerar que la ausencia de nuevas alarmas significa que la situación está resuelta"], correct:1, expl:"Una situación no resuelta cuando se acerca el plazo reglamentario debe informarse sin esperar, exactamente como el principio ERM ya aplicado en otros contextos: el aislamiento ante una incertidumbre prolongada es un factor de riesgo, no una prueba de competencia." },
    ],
    pt: [
      { q:"És o oficial de máquinas de quarto em configuração UMS (casa das máquinas sem vigilância). Um alarme crítico dispara a meio da noite enquanto não te encontras fisicamente na casa das máquinas. Qual é a tua prioridade imediata?", opts:["Esperar um segundo alarme para confirmar antes de te deslocares","Dirigir-te sem demora à casa das máquinas para avaliar e tratar o alarme, respeitando o prazo de resposta regulamentar UMS","Contactar primeiro o Chefe de Máquinas antes de qualquer deslocação","Rearmar o alarme à distância sem verificação física"], correct:1, expl:"Um alarme crítico em configuração UMS impõe uma resposta física sem demora, respeitando o tempo de resposta regulamentar — rearmar sem verificação ou esperar por confirmação adicional expõe a deixar evoluir sem vigilância uma situação perigosa." },
      { q:"Ao chegar, constatas que vários alarmes secundários também dispararam em cascata, além do alarme inicial. Não consegues tratar tudo simultaneamente sozinho. Como proceder?", opts:["Tratar os alarmes por ordem cronológica de disparo, sem distinção","Identificar e tratar primeiro o alarme que representa o risco mais crítico para a segurança do navio ou das pessoas, já que os alarmes secundários são frequentemente consequência do primeiro","Rearmar todos os alarmes secundários para te concentrares no primeiro","Esperar por reforços antes de tratar seja o que for"], correct:1, expl:"Uma cascata de alarmes é frequentemente consequência de um único evento raiz — a priorização deve visar primeiro o risco mais crítico, já que os alarmes secundários podem resolver-se uma vez tratada a causa principal, em vez de os tratar sem critério pela ordem de chegada." },
      { q:"O prazo de resposta regulamentar UMS aproxima-se e ainda não conseguiste resolver nem diagnosticar totalmente a situação sozinho. Qual é a boa prática?", opts:["Continuar sozinho indefinidamente, pedir ajuda seria uma admissão de fracasso","Alertar o Chefe de Máquinas e a ponte da situação em curso, mesmo não resolvida, para não ficares sozinho perante uma incerteza prolongada","Esperar que o prazo seja largamente ultrapassado antes de considerar alertar","Considerar que a ausência de novos alarmes significa que a situação está resolvida"], correct:1, expl:"Uma situação não resolvida à aproximação do prazo regulamentar deve ser reportada sem esperar, exatamente como o princípio ERM já aplicado noutros contextos: o isolamento perante uma incerteza prolongada é um fator de risco, não uma prova de competência." },
    ],
  },
};
