// @ts-nocheck
// ── examSummaryQuestions.ts ─────────────────────────────────────
// CONTENT ONLY — 13th exam ("Foundation Summary") question pool, drafted
// 2026-09-04 per explicit user validation of the 6-theme plan below. This
// file is NOT imported or wired anywhere yet (no page, no unlock logic, no
// examQuestionPools.ts integration) — per standing doctrine, content
// approval is not approval to build engine/UI. That is a separate,
// explicitly-gated next step.
//
// Doctrine applied to theme 3 (SOLAS/MARPOL obligations), per explicit user
// instruction: same non-attribution caution as d1-d6 — the regulatory
// CONCEPT can be tested and the convention NAMES (SOLAS, MARPOL) can be
// referenced directly, exactly as d2's own approved lesson content already
// does (LessonSOLAS.tsx, LessonMARPOLLegal.tsx, left untouched by the
// earlier IMO/OMI reformulation pass). What is avoided is attributing
// authority to the organization itself — no "according to IMO", no bare
// "IMO"/"OMI" acronym anywhere in this file.
//
// Each theme is a single cross-domain scenario spanning 3-4 already-taught
// Deck/Safety modules, testing synthesis and prioritization under
// pressure — not re-testing facts already covered by each module's own
// mini-exam. 20 questions total across 6 themes (4+3+3+3+4+3), quadrilingual.

const LANGS = ["fr", "en", "es", "pt"];

export const SUMMARY_THEMES_META = [
  { id: "theme1_collision_weather", modules: ["d1-l8", "s1", "d7", "d1-l2", "d6"] },
  { id: "theme2_hull_damage", modules: ["d1-l2", "d6", "s1", "s6"] },
  { id: "theme3_fire_legal", modules: ["s4", "d4", "d2", "s6"] },
  { id: "theme4_medical_coordination", modules: ["s3", "d3", "s2", "d4"] },
  { id: "theme5_abandon_ship", modules: ["d7", "d1-l2", "d6", "s5", "s1", "s2"] },
  { id: "theme6_restricted_visibility", modules: ["d3", "d1-l8", "s1", "d4", "s6"] },
];

export const SUMMARY_QUESTIONS = {
  // ══════════════════════════════════════
  // THEME 1 — Collision risk in deteriorating weather
  // (COLREG + Meteorology + Stability + Team safety reflex)
  // ══════════════════════════════════════
  theme1_collision_weather: {
    fr: [
      { q:"Vous naviguez de nuit dans une zone de trafic dense. La pression barométrique chute rapidement et la visibilité se dégrade. Un navire est détecté par radar avec un risque de collision. Quelle est votre priorité immédiate ?", opts:["Attendre que la météo se stabilise avant d'agir","Appliquer immédiatement les règles de barre et de route appropriées à la situation de rencontre, tout en surveillant l'évolution météo","Réduire la vitesse à zéro sans manœuvre","Contacter l'armateur avant toute décision"], correct:1, expl:"Le risque de collision reste la priorité absolue, quelle que soit l'évolution météo en parallèle — la manœuvre COLREG appropriée doit être engagée sans délai, tout en gardant la dégradation météo sous surveillance." },
      { q:"Votre navire a un GM proche du minimum réglementaire. Une dépression se creuse rapidement et un risque de collision est détecté simultanément. Que devez-vous garder à l'esprit avant toute manœuvre d'évitement brusque ?", opts:["Rien de particulier, la manœuvre COLREG prime toujours sans réserve","Une manœuvre de barre trop brutale peut aggraver une stabilité déjà réduite — la manœuvre doit rester efficace mais maîtrisée","Il faut d'abord reballaster avant toute manœuvre","La stabilité n'a aucun lien avec les manœuvres d'évitement"], correct:1, expl:"Une stabilité déjà réduite (GM proche du minimum) impose de rester vigilant sur l'amplitude des manœuvres de barre, même si l'action d'évitement reste non négociable — une gîte excessive dans une manœuvre brusque peut créer un second risque." },
      { q:"Vous êtes officier de quart. Un risque de collision se précise alors que le baromètre chute et que le vent forcit rapidement. Vous hésitez à alerter le Commandant, pensant pouvoir gérer seul la situation. Quel réflexe de sécurité s'applique ici ?", opts:["Continuer seul, déranger le Commandant serait mal vu","Signaler immédiatement la situation combinée — un risque de collision cumulé à une dégradation météo justifie toujours l'alerte, sans hésitation liée à la hiérarchie","Attendre que la situation s'aggrave encore pour être sûr","Résoudre d'abord le problème météo avant de mentionner le risque de collision"], correct:1, expl:"L'hésitation à signaler par respect de la hiérarchie est précisément le phénomène qui doit être surmonté dans une situation à risques cumulés — la combinaison collision + météo dégradée justifie une alerte immédiate et sans délai." },
      { q:"Après une manœuvre d'évitement réussie sous vent fort, le risque de collision est écarté mais la météo continue de se dégrader. Quelle est la bonne pratique immédiate ?", opts:["Considérer l'incident clos et reprendre la route initiale sans réévaluation","Réévaluer la situation dans son ensemble — la fin du risque de collision ne signifie pas la fin de la vigilance nécessaire face à la météo dégradée","Réduire immédiatement l'équipage de quart","Ignorer la météo puisque la manœuvre a réussi"], correct:1, expl:"La réévaluation continue est un réflexe central : la résolution d'un risque ne doit jamais faire retomber la vigilance sur les autres facteurs actifs, ici la météo qui continue de se dégrader." },
    ],
    en: [
      { q:"You are navigating at night in a busy traffic area. Barometric pressure is dropping rapidly and visibility is deteriorating. Radar detects a vessel with a risk of collision. What is your immediate priority?", opts:["Wait for the weather to stabilize before acting","Apply the appropriate steering and sailing rules for the encounter situation immediately, while monitoring the weather development","Reduce speed to zero without maneuvering","Contact the owner before any decision"], correct:1, expl:"Collision risk remains the absolute priority regardless of the parallel weather deterioration — the appropriate COLREG maneuver must be initiated without delay, while keeping the weather situation under watch." },
      { q:"Your vessel's GM is close to the regulatory minimum. A depression is deepening rapidly and a collision risk is detected at the same time. What must you keep in mind before any abrupt avoidance maneuver?", opts:["Nothing in particular, the COLREG maneuver always takes priority without reservation","An overly abrupt helm maneuver can worsen an already reduced stability — the maneuver must remain effective but controlled","Reballasting must happen before any maneuver","Stability has no connection to avoidance maneuvers"], correct:1, expl:"Already-reduced stability (GM near the minimum) requires staying mindful of the amplitude of helm maneuvers, even though the avoidance action itself remains non-negotiable — excessive heel during an abrupt maneuver can create a second risk." },
      { q:"You are the officer of the watch. A collision risk is developing while the barometer drops and the wind strengthens rapidly. You hesitate to alert the Captain, thinking you can handle the situation alone. Which safety reflex applies here?", opts:["Continue alone, disturbing the Captain would be poorly received","Report the combined situation immediately — a collision risk compounded by deteriorating weather always justifies the alert, without hesitation linked to hierarchy","Wait for the situation to worsen further to be certain","Resolve the weather problem first before mentioning the collision risk"], correct:1, expl:"Hesitating to report out of respect for hierarchy is precisely the phenomenon that must be overcome in a compounded-risk situation — collision risk combined with deteriorating weather justifies an immediate, unhesitating alert." },
      { q:"After a successful avoidance maneuver in strong wind, the collision risk is cleared but the weather continues to deteriorate. What is the correct immediate practice?", opts:["Consider the incident closed and resume the original course without reassessment","Reassess the overall situation — the end of the collision risk does not mean the end of the vigilance required for the deteriorating weather","Immediately reduce the watch crew","Ignore the weather since the maneuver succeeded"], correct:1, expl:"Continuous reassessment is a central reflex: resolving one risk must never lower vigilance on other active factors — here, the weather, which continues to deteriorate." },
    ],
    es: [
      { q:"Navegas de noche en una zona de tráfico denso. La presión barométrica cae rápidamente y la visibilidad se degrada. El radar detecta un buque con riesgo de colisión. ¿Cuál es tu prioridad inmediata?", opts:["Esperar a que el tiempo se estabilice antes de actuar","Aplicar de inmediato las reglas de gobierno y rumbo apropiadas para la situación de encuentro, mientras se vigila la evolución meteorológica","Reducir la velocidad a cero sin maniobrar","Contactar al armador antes de cualquier decisión"], correct:1, expl:"El riesgo de colisión sigue siendo la prioridad absoluta, sea cual sea la evolución meteorológica en paralelo — la maniobra COLREG apropiada debe iniciarse sin demora, vigilando a la vez el deterioro meteorológico." },
      { q:"Tu buque tiene un GM cercano al mínimo reglamentario. Una depresión se profundiza rápidamente y se detecta simultáneamente un riesgo de colisión. ¿Qué debes tener presente antes de cualquier maniobra brusca de evasión?", opts:["Nada en particular, la maniobra COLREG siempre prevalece sin reserva","Una maniobra de timón demasiado brusca puede agravar una estabilidad ya reducida — la maniobra debe seguir siendo eficaz pero controlada","Hay que relastrar antes de cualquier maniobra","La estabilidad no tiene ninguna relación con las maniobras de evasión"], correct:1, expl:"Una estabilidad ya reducida (GM cercano al mínimo) exige mantenerse atento a la amplitud de las maniobras de timón, aunque la acción de evasión en sí siga siendo innegociable — una escora excesiva en una maniobra brusca puede crear un segundo riesgo." },
      { q:"Eres el oficial de guardia. Se perfila un riesgo de colisión mientras el barómetro cae y el viento arrecia rápidamente. Dudas en alertar al Capitán, pensando que puedes gestionar la situación solo. ¿Qué reflejo de seguridad se aplica aquí?", opts:["Continuar solo, molestar al Capitán se vería mal","Informar de inmediato de la situación combinada — un riesgo de colisión sumado a un deterioro meteorológico siempre justifica la alerta, sin dudar por la jerarquía","Esperar a que la situación empeore más para estar seguro","Resolver primero el problema meteorológico antes de mencionar el riesgo de colisión"], correct:1, expl:"La duda en informar por respeto a la jerarquía es precisamente el fenómeno que debe superarse en una situación de riesgos acumulados — la combinación de colisión y meteorología degradada justifica una alerta inmediata y sin dudar." },
      { q:"Tras una maniobra de evasión exitosa con viento fuerte, el riesgo de colisión desaparece pero el tiempo sigue empeorando. ¿Cuál es la buena práctica inmediata?", opts:["Considerar el incidente cerrado y retomar el rumbo inicial sin reevaluación","Reevaluar la situación en su conjunto — el fin del riesgo de colisión no significa el fin de la vigilancia necesaria ante el tiempo degradado","Reducir de inmediato la tripulación de guardia","Ignorar el tiempo puesto que la maniobra tuvo éxito"], correct:1, expl:"La reevaluación continua es un reflejo central: resolver un riesgo nunca debe hacer bajar la vigilancia sobre los demás factores activos, aquí el tiempo, que sigue empeorando." },
    ],
    pt: [
      { q:"Navegas à noite numa zona de tráfego denso. A pressão barométrica cai rapidamente e a visibilidade degrada-se. O radar deteta um navio com risco de colisão. Qual é a tua prioridade imediata?", opts:["Esperar que o tempo estabilize antes de agir","Aplicar de imediato as regras de governo e rumo apropriadas à situação de encontro, vigiando ao mesmo tempo a evolução meteorológica","Reduzir a velocidade a zero sem manobrar","Contactar o armador antes de qualquer decisão"], correct:1, expl:"O risco de colisão continua a ser a prioridade absoluta, seja qual for a evolução meteorológica em paralelo — a manobra COLREG apropriada deve ser iniciada sem demora, mantendo a degradação meteorológica sob vigilância." },
      { q:"O teu navio tem um GM próximo do mínimo regulamentar. Uma depressão aprofunda-se rapidamente e um risco de colisão é detetado simultaneamente. O que deves ter em mente antes de qualquer manobra brusca de evasão?", opts:["Nada em particular, a manobra COLREG prevalece sempre sem reserva","Uma manobra de leme demasiado brusca pode agravar uma estabilidade já reduzida — a manobra deve continuar eficaz mas controlada","É preciso relastrar antes de qualquer manobra","A estabilidade não tem qualquer relação com as manobras de evasão"], correct:1, expl:"Uma estabilidade já reduzida (GM próximo do mínimo) exige manter atenção à amplitude das manobras de leme, embora a ação de evasão em si continue a ser inegociável — um adornamento excessivo numa manobra brusca pode criar um segundo risco." },
      { q:"És o oficial de quarto. Um risco de colisão perfila-se enquanto o barómetro cai e o vento aumenta rapidamente. Hesitas em alertar o Comandante, pensando poder gerir sozinho a situação. Que reflexo de segurança se aplica aqui?", opts:["Continuar sozinho, incomodar o Comandante seria mal visto","Reportar de imediato a situação combinada — um risco de colisão somado a uma meteorologia degradada justifica sempre o alerta, sem hesitação ligada à hierarquia","Esperar que a situação piore ainda mais para ter certeza","Resolver primeiro o problema meteorológico antes de mencionar o risco de colisão"], correct:1, expl:"A hesitação em reportar por respeito à hierarquia é precisamente o fenómeno que deve ser superado numa situação de riscos acumulados — a combinação de colisão e meteorologia degradada justifica um alerta imediato e sem hesitação." },
      { q:"Após uma manobra de evasão bem-sucedida com vento forte, o risco de colisão é afastado mas o tempo continua a degradar-se. Qual é a boa prática imediata?", opts:["Considerar o incidente encerrado e retomar a rota inicial sem reavaliação","Reavaliar a situação no seu conjunto — o fim do risco de colisão não significa o fim da vigilância necessária face ao tempo degradado","Reduzir de imediato a tripulação de quarto","Ignorar o tempo já que a manobra foi bem-sucedida"], correct:1, expl:"A reavaliação contínua é um reflexo central: a resolução de um risco nunca deve fazer baixar a vigilância sobre os outros fatores ativos, aqui o tempo, que continua a degradar-se." },
    ],
  },

  // ══════════════════════════════════════
  // THEME 2 — Hull damage / grounding response
  // (Stability & SOLAS compartmentation + Seamanship + First-minutes response + Damage control)
  // ══════════════════════════════════════
  theme2_hull_damage: {
    fr: [
      { q:"Votre navire talonne légèrement sur un haut-fond en zone côtière. Aucune voie d'eau visible n'est immédiatement détectée. Quelle est votre première action ?", opts:["Continuer la route normalement puisqu'aucun dégât n'est visible","Évaluer immédiatement l'impact potentiel sur le compartimentage étanche et vérifier l'absence de voie d'eau avant toute reprise de route","Attendre l'escale suivante pour inspecter la coque","Augmenter la vitesse pour quitter la zone rapidement"], correct:1, expl:"Un contact avec le fond, même léger, impose une vérification immédiate de l'intégrité de la coque et du compartimentage avant toute reprise normale de la navigation — l'absence de dégât visible en surface ne garantit rien." },
      { q:"Une voie d'eau est confirmée après un talonnage. Le mouillage semble une option pour stabiliser la situation. Quel facteur doit peser sur cette décision ?", opts:["Le mouillage est toujours la meilleure option en cas de voie d'eau","La nature du fond et la profondeur doivent être évaluées avant de mouiller, car un mouillage mal engagé peut aggraver la situation plutôt que la stabiliser","Le mouillage n'a aucun lien avec une voie d'eau","Il faut mouiller uniquement si l'armateur l'autorise"], correct:1, expl:"Le choix de mouiller reste une décision technique dépendant du fond et de la profondeur — un mouillage mal préparé peut ajouter un risque supplémentaire plutôt que stabiliser la situation." },
      { q:"Dans les toutes premières minutes après la confirmation d'une voie d'eau, plusieurs tâches se présentent : fermeture des portes étanches, vérification de l'équipage, message de détresse. Quel principe guide l'ordre de ces actions ?", opts:["L'ordre n'a aucune importance, tout peut être fait simultanément par une seule personne","Une checklist structurée évite de perdre un temps précieux à décider quoi faire en premier dans une fenêtre souvent très courte","Le message de détresse doit toujours attendre la fin de l'inspection complète du navire","Seul le Commandant peut fermer une porte étanche"], correct:1, expl:"Une checklist structurée (sécurité, dangers, étanchéité, équipage, détresse, coordination) permet d'agir vite et dans le bon ordre sans perdre de temps à réfléchir à chaque étape au milieu de l'urgence." },
    ],
    en: [
      { q:"Your vessel lightly touches bottom on a shoal in a coastal area. No visible leak is immediately detected. What is your first action?", opts:["Continue the normal course since no damage is visible","Immediately assess the potential impact on watertight compartmentation and check for any leak before resuming the course","Wait until the next port call to inspect the hull","Increase speed to leave the area quickly"], correct:1, expl:"Any contact with the bottom, even light, requires an immediate check of hull integrity and compartmentation before resuming normal navigation — the absence of visible surface damage guarantees nothing." },
      { q:"A leak is confirmed after touching bottom. Anchoring seems like an option to stabilize the situation. What factor must weigh on this decision?", opts:["Anchoring is always the best option in case of a leak","The nature of the seabed and the depth must be assessed before anchoring, as a poorly executed anchoring can worsen the situation rather than stabilize it","Anchoring has no connection to a leak","Anchoring should only happen if the owner authorizes it"], correct:1, expl:"The decision to anchor remains a technical one depending on the seabed and depth — a poorly prepared anchoring can add a further risk rather than stabilize the situation." },
      { q:"In the very first minutes after a leak is confirmed, several tasks arise: closing watertight doors, checking the crew, a distress message. What principle guides the order of these actions?", opts:["The order doesn't matter, everything can be done simultaneously by one person","A structured checklist avoids wasting precious time deciding what to do first in an often very short window","The distress message must always wait until the full ship inspection is complete","Only the Captain can close a watertight door"], correct:1, expl:"A structured checklist (safety, dangers, watertightness, crew, distress, coordination) allows acting quickly and in the right order without wasting time thinking through each step in the middle of the emergency." },
    ],
    es: [
      { q:"Tu buque toca ligeramente fondo en un bajío en zona costera. No se detecta de inmediato ninguna vía de agua visible. ¿Cuál es tu primera acción?", opts:["Continuar el rumbo normal ya que no se ve ningún daño","Evaluar de inmediato el impacto potencial en el compartimentado estanco y verificar la ausencia de vía de agua antes de retomar el rumbo","Esperar a la siguiente escala para inspeccionar el casco","Aumentar la velocidad para salir rápido de la zona"], correct:1, expl:"Cualquier contacto con el fondo, incluso leve, exige una verificación inmediata de la integridad del casco y del compartimentado antes de retomar la navegación normal — la ausencia de daño visible en superficie no garantiza nada." },
      { q:"Se confirma una vía de agua tras el toque de fondo. Fondear parece una opción para estabilizar la situación. ¿Qué factor debe pesar en esta decisión?", opts:["Fondear siempre es la mejor opción en caso de vía de agua","La naturaleza del fondo y la profundidad deben evaluarse antes de fondear, ya que un fondeo mal ejecutado puede agravar la situación en vez de estabilizarla","Fondear no tiene relación alguna con una vía de agua","Solo se debe fondear si el armador lo autoriza"], correct:1, expl:"La decisión de fondear sigue siendo técnica y depende del fondo y la profundidad — un fondeo mal preparado puede añadir un riesgo adicional en vez de estabilizar la situación." },
      { q:"En los primerísimos minutos tras confirmarse una vía de agua, surgen varias tareas: cerrar puertas estancas, verificar a la tripulación, mensaje de socorro. ¿Qué principio guía el orden de estas acciones?", opts:["El orden no importa, todo puede hacerlo una sola persona simultáneamente","Una lista de verificación estructurada evita perder un tiempo precioso decidiendo qué hacer primero en una ventana a menudo muy corta","El mensaje de socorro siempre debe esperar a que termine la inspección completa del buque","Solo el Capitán puede cerrar una puerta estanca"], correct:1, expl:"Una lista de verificación estructurada (seguridad, peligros, estanqueidad, tripulación, socorro, coordinación) permite actuar rápido y en el orden correcto sin perder tiempo pensando cada paso en medio de la emergencia." },
    ],
    pt: [
      { q:"O teu navio toca ligeiramente o fundo num baixio em zona costeira. Nenhuma via de água visível é imediatamente detetada. Qual é a tua primeira ação?", opts:["Continuar a rota normal já que nenhum dano é visível","Avaliar de imediato o impacto potencial no compartimentado estanque e verificar a ausência de via de água antes de retomar a rota","Esperar pela próxima escala para inspecionar o casco","Aumentar a velocidade para sair rapidamente da zona"], correct:1, expl:"Qualquer contacto com o fundo, mesmo ligeiro, exige uma verificação imediata da integridade do casco e do compartimentado antes de retomar a navegação normal — a ausência de dano visível à superfície não garante nada." },
      { q:"Confirma-se uma via de água após o toque no fundo. Fundear parece uma opção para estabilizar a situação. Que fator deve pesar nesta decisão?", opts:["Fundear é sempre a melhor opção em caso de via de água","A natureza do fundo e a profundidade devem ser avaliadas antes de fundear, pois um fundeio mal executado pode agravar a situação em vez de a estabilizar","Fundear não tem qualquer relação com uma via de água","Só se deve fundear se o armador autorizar"], correct:1, expl:"A decisão de fundear continua a ser técnica e depende do fundo e da profundidade — um fundeio mal preparado pode acrescentar um risco adicional em vez de estabilizar a situação." },
      { q:"Nos primeiríssimos minutos após a confirmação de uma via de água, surgem várias tarefas: fechar portas estanques, verificar a tripulação, mensagem de socorro. Que princípio orienta a ordem destas ações?", opts:["A ordem não importa, tudo pode ser feito simultaneamente por uma só pessoa","Uma checklist estruturada evita perder tempo precioso a decidir o que fazer primeiro numa janela muitas vezes muito curta","A mensagem de socorro deve sempre esperar até ao fim da inspeção completa do navio","Só o Comandante pode fechar uma porta estanque"], correct:1, expl:"Uma checklist estruturada (segurança, perigos, estanqueidade, tripulação, socorro, coordenação) permite agir rápido e pela ordem certa sem perder tempo a pensar em cada passo no meio da emergência." },
    ],
  },

  // ══════════════════════════════════════
  // THEME 3 — Onboard fire with legal/communication stakes
  // (Firefighting + SMCP + SOLAS/MARPOL reporting obligations + Permit-to-work)
  // Non-attribution doctrine applied: SOLAS/MARPOL referenced as convention
  // names only (matching d2's approved content), never "IMO"/"OMI".
  // ══════════════════════════════════════
  theme3_fire_legal: {
    fr: [
      { q:"Une nappe d'hydrocarbures accidentelle se forme en mer suite à une fuite de soute pendant une opération de transfert. Quelle est l'obligation immédiate, au titre des obligations de prévention de la pollution couvertes par MARPOL ?", opts:["Attendre l'escale suivante pour signaler l'incident","Stopper immédiatement la source de la fuite et déclencher sans délai la procédure de signalement de pollution","Ne rien signaler si la nappe semble limitée","Attendre l'autorisation de l'armateur avant toute action corrective"], correct:1, expl:"Toute pollution accidentelle par hydrocarbures impose un arrêt immédiat de la source et un signalement sans délai — les obligations MARPOL en matière de prévention de la pollution ne laissent aucune place à l'attente." },
      { q:"Après un incendie maîtrisé en salle des machines, quel type d'information un compte-rendu conforme aux obligations SOLAS de sécurité doit-il impérativement inclure ?", opts:["Uniquement le nom du responsable présumé","La nature de l'incident, les actions prises et l'état actuel du navire, de manière claire et complète","Rien tant que l'enquête interne n'est pas terminée","Seulement la durée de l'incendie"], correct:1, expl:"Un compte-rendu de sécurité complet — nature de l'incident, actions engagées, état actuel du navire — est ce qu'exige une communication de sécurité rigoureuse après un événement de ce type." },
      { q:"Le permis de travail à chaud n'avait pas été correctement complété avant l'incident. Quel enseignement structurel s'impose pour l'avenir, indépendamment de la question des responsabilités individuelles ?", opts:["Aucun changement n'est nécessaire si l'incendie a été maîtrisé avec succès","Le respect systématique du permis de travail et de l'évaluation des risques associée reste la meilleure prévention contre ce type d'incident","Il suffit de sanctionner la personne responsable","Le permis de travail est une simple formalité sans lien réel avec la prévention"], correct:1, expl:"Le respect rigoureux du permis de travail et de l'évaluation des risques est la mesure structurelle la plus efficace pour prévenir ce type d'incident, au-delà de la question de responsabilité individuelle." },
    ],
    en: [
      { q:"An accidental oil slick forms at sea following a bunker leak during a transfer operation. What is the immediate obligation, under the pollution-prevention duties covered by MARPOL?", opts:["Wait for the next port call to report the incident","Immediately stop the source of the leak and initiate the pollution reporting procedure without delay","Report nothing if the slick seems limited","Wait for the owner's authorization before any corrective action"], correct:1, expl:"Any accidental oil pollution requires immediately stopping the source and reporting without delay — MARPOL's pollution-prevention obligations leave no room for waiting." },
      { q:"After a fire is brought under control in the engine room, what type of information must a report compliant with SOLAS safety obligations necessarily include?", opts:["Only the name of the presumed responsible person","The nature of the incident, the actions taken, and the current state of the vessel, clearly and completely","Nothing until the internal investigation is complete","Only the duration of the fire"], correct:1, expl:"A complete safety report — nature of the incident, actions taken, current state of the vessel — is what rigorous safety communication requires after an event of this kind." },
      { q:"The hot work permit had not been properly completed before the incident. What structural lesson applies for the future, independent of individual responsibility?", opts:["No change is needed if the fire was successfully brought under control","Systematic compliance with the work permit and its associated risk assessment remains the best prevention against this type of incident","It's enough to sanction the responsible person","The work permit is a mere formality with no real link to prevention"], correct:1, expl:"Rigorous compliance with the work permit and risk assessment is the most effective structural measure to prevent this type of incident, beyond the question of individual responsibility." },
    ],
    es: [
      { q:"Se forma una mancha de hidrocarburos accidental en el mar tras una fuga de combustible durante una operación de transferencia. ¿Cuál es la obligación inmediata, dentro de los deberes de prevención de la contaminación cubiertos por MARPOL?", opts:["Esperar a la siguiente escala para informar del incidente","Detener de inmediato la fuente de la fuga e iniciar sin demora el procedimiento de notificación de contaminación","No informar si la mancha parece limitada","Esperar la autorización del armador antes de cualquier acción correctiva"], correct:1, expl:"Cualquier contaminación accidental por hidrocarburos exige detener de inmediato la fuente e informar sin demora — las obligaciones de MARPOL en materia de prevención de la contaminación no dejan margen para esperar." },
      { q:"Tras controlar un incendio en la sala de máquinas, ¿qué tipo de información debe incluir obligatoriamente un informe conforme a las obligaciones de seguridad de SOLAS?", opts:["Solo el nombre del presunto responsable","La naturaleza del incidente, las acciones tomadas y el estado actual del buque, de forma clara y completa","Nada hasta que termine la investigación interna","Solo la duración del incendio"], correct:1, expl:"Un informe de seguridad completo — naturaleza del incidente, acciones tomadas, estado actual del buque — es lo que exige una comunicación de seguridad rigurosa tras un evento de este tipo." },
      { q:"El permiso de trabajo en caliente no se había completado correctamente antes del incidente. ¿Qué lección estructural se impone para el futuro, independientemente de la cuestión de responsabilidades individuales?", opts:["No es necesario ningún cambio si el incendio se controló con éxito","El cumplimiento sistemático del permiso de trabajo y de la evaluación de riesgos asociada sigue siendo la mejor prevención contra este tipo de incidente","Basta con sancionar a la persona responsable","El permiso de trabajo es una simple formalidad sin relación real con la prevención"], correct:1, expl:"El cumplimiento riguroso del permiso de trabajo y de la evaluación de riesgos es la medida estructural más eficaz para prevenir este tipo de incidente, más allá de la cuestión de la responsabilidad individual." },
    ],
    pt: [
      { q:"Forma-se uma mancha de hidrocarbonetos acidental no mar após uma fuga de combustível durante uma operação de transferência. Qual é a obrigação imediata, no âmbito dos deveres de prevenção da poluição abrangidos pela MARPOL?", opts:["Esperar pela próxima escala para reportar o incidente","Parar de imediato a fonte da fuga e desencadear sem demora o procedimento de notificação de poluição","Não reportar se a mancha parecer limitada","Esperar pela autorização do armador antes de qualquer ação corretiva"], correct:1, expl:"Qualquer poluição acidental por hidrocarbonetos exige parar de imediato a fonte e reportar sem demora — as obrigações da MARPOL em matéria de prevenção da poluição não deixam margem para esperar." },
      { q:"Depois de um incêndio controlado na casa das máquinas, que tipo de informação deve um relatório conforme às obrigações de segurança da SOLAS incluir obrigatoriamente?", opts:["Apenas o nome do presumível responsável","A natureza do incidente, as ações tomadas e o estado atual do navio, de forma clara e completa","Nada até a investigação interna terminar","Apenas a duração do incêndio"], correct:1, expl:"Um relatório de segurança completo — natureza do incidente, ações tomadas, estado atual do navio — é o que uma comunicação de segurança rigorosa exige após um evento deste tipo." },
      { q:"A autorização de trabalho a quente não tinha sido corretamente preenchida antes do incidente. Que lição estrutural se impõe para o futuro, independentemente da questão das responsabilidades individuais?", opts:["Nenhuma mudança é necessária se o incêndio foi controlado com sucesso","O cumprimento sistemático da autorização de trabalho e da avaliação de riscos associada continua a ser a melhor prevenção contra este tipo de incidente","Basta sancionar a pessoa responsável","A autorização de trabalho é uma mera formalidade sem relação real com a prevenção"], correct:1, expl:"O cumprimento rigoroso da autorização de trabalho e da avaliação de riscos é a medida estrutural mais eficaz para prevenir este tipo de incidente, para além da questão da responsabilidade individual." },
    ],
  },

  // ══════════════════════════════════════
  // THEME 4 — Medical emergency requiring external coordination
  // (First Aid + GMDSS/radio medical advice + SMCP medical phraseology)
  // ══════════════════════════════════════
  theme4_medical_coordination: {
    fr: [
      { q:"Un membre d'équipage s'effondre soudainement et ne répond ni à la voix ni à la douleur. Quelle est la première action, avant même de penser à contacter une assistance médicale externe ?", opts:["Contacter immédiatement l'assistance médicale radio avant tout geste","Sécuriser la scène et débuter l'évaluation primaire (DRABC) sans délai","Attendre l'arrivée d'un officier supérieur","Déplacer la victime vers l'infirmerie avant toute évaluation"], correct:1, expl:"L'évaluation primaire immédiate (DRABC) reste la priorité absolue avant toute autre démarche, y compris la prise de contact avec une assistance externe — chaque seconde compte pour un bilan fiable." },
      { q:"Une fois les premiers gestes réalisés, un avis médical radio est nécessaire. Quelle est la bonne pratique de communication dans ce contexte ?", opts:["Décrire la situation de façon informelle et détaillée sans structure particulière","Utiliser la phraséologie normalisée pour transmettre un état clair et structuré de la victime, permettant une réponse médicale rapide et adaptée","Ne contacter l'assistance médicale que si l'état empire","Transmettre uniquement le nom de la victime dans un premier temps"], correct:1, expl:"La phraséologie normalisée permet une transmission rapide et sans ambiguïté de l'état du patient, condition essentielle pour recevoir un avis médical adapté dans les meilleurs délais." },
      { q:"L'avis médical radio recommande une surveillance rapprochée en attendant une décision sur une éventuelle évacuation médicale. Quel est le bon réflexe pour l'équipe à bord ?", opts:["Considérer que le rôle de l'équipe s'arrête après la transmission de l'avis médical","Poursuivre une surveillance active et structurée de l'état du patient, en documentant toute évolution pour informer la suite de la prise en charge","Attendre passivement sans réévaluer l'état du patient","Cesser toute communication avec l'assistance médicale radio jusqu'à l'escale"], correct:1, expl:"La surveillance active et la documentation continue de l'état du patient permettent d'informer efficacement toute décision ultérieure, y compris une éventuelle évacuation médicale." },
    ],
    en: [
      { q:"A crew member suddenly collapses and responds neither to voice nor to pain. What is the first action, even before thinking about contacting external medical assistance?", opts:["Immediately contact radio medical assistance before any other action","Secure the scene and begin the primary assessment (DRABC) without delay","Wait for a senior officer to arrive","Move the casualty to the infirmary before any assessment"], correct:1, expl:"The immediate primary assessment (DRABC) remains the absolute priority before any other step, including contacting external assistance — every second counts for a reliable assessment." },
      { q:"Once first aid actions are performed, radio medical advice is needed. What is the correct communication practice in this context?", opts:["Describe the situation informally and in detail without any particular structure","Use standardized phraseology to convey a clear, structured status of the casualty, enabling a fast and appropriate medical response","Only contact medical assistance if the condition worsens","Only transmit the casualty's name at first"], correct:1, expl:"Standardized phraseology enables a fast, unambiguous transmission of the patient's status — an essential condition for receiving appropriate medical advice as quickly as possible." },
      { q:"The radio medical advice recommends close monitoring while awaiting a decision on a possible medical evacuation. What is the correct reflex for the onboard team?", opts:["Consider the team's role over once the medical advice has been transmitted","Continue active, structured monitoring of the patient's condition, documenting any change to inform the next steps of care","Wait passively without reassessing the patient's condition","Stop all communication with radio medical assistance until the port call"], correct:1, expl:"Active monitoring and continuous documentation of the patient's condition effectively informs any subsequent decision, including a possible medical evacuation." },
    ],
    es: [
      { q:"Un miembro de la tripulación se desploma de repente y no responde ni a la voz ni al dolor. ¿Cuál es la primera acción, incluso antes de pensar en contactar con asistencia médica externa?", opts:["Contactar de inmediato con la asistencia médica por radio antes de cualquier otra acción","Asegurar la escena e iniciar la evaluación primaria (DRABC) sin demora","Esperar a que llegue un oficial superior","Trasladar a la víctima a la enfermería antes de cualquier evaluación"], correct:1, expl:"La evaluación primaria inmediata (DRABC) sigue siendo la prioridad absoluta antes de cualquier otro paso, incluido el contacto con asistencia externa — cada segundo cuenta para una valoración fiable." },
      { q:"Una vez realizados los primeros gestos, se necesita un asesoramiento médico por radio. ¿Cuál es la práctica de comunicación correcta en este contexto?", opts:["Describir la situación de forma informal y detallada sin ninguna estructura particular","Usar la fraseología normalizada para transmitir un estado claro y estructurado de la víctima, permitiendo una respuesta médica rápida y adecuada","Solo contactar con la asistencia médica si el estado empeora","Transmitir solo el nombre de la víctima en un primer momento"], correct:1, expl:"La fraseología normalizada permite una transmisión rápida y sin ambigüedad del estado del paciente, condición esencial para recibir un asesoramiento médico adecuado lo antes posible." },
      { q:"El asesoramiento médico por radio recomienda una vigilancia estrecha mientras se decide sobre una posible evacuación médica. ¿Cuál es el reflejo correcto para el equipo a bordo?", opts:["Considerar que el papel del equipo termina tras transmitir el asesoramiento médico","Continuar una vigilancia activa y estructurada del estado del paciente, documentando cualquier evolución para informar la atención posterior","Esperar pasivamente sin reevaluar el estado del paciente","Cesar toda comunicación con la asistencia médica por radio hasta la escala"], correct:1, expl:"La vigilancia activa y la documentación continua del estado del paciente permiten informar eficazmente cualquier decisión posterior, incluida una posible evacuación médica." },
    ],
    pt: [
      { q:"Um membro da tripulação desmaia subitamente e não responde nem à voz nem à dor. Qual é a primeira ação, mesmo antes de pensar em contactar assistência médica externa?", opts:["Contactar de imediato a assistência médica por rádio antes de qualquer outra ação","Garantir a segurança da cena e iniciar a avaliação primária (DRABC) sem demora","Esperar que chegue um oficial superior","Deslocar o sinistrado para a enfermaria antes de qualquer avaliação"], correct:1, expl:"A avaliação primária imediata (DRABC) continua a ser a prioridade absoluta antes de qualquer outro passo, incluindo o contacto com assistência externa — cada segundo conta para uma avaliação fiável." },
      { q:"Depois de realizados os primeiros gestos, é necessário um aconselhamento médico por rádio. Qual é a boa prática de comunicação neste contexto?", opts:["Descrever a situação de forma informal e detalhada sem qualquer estrutura particular","Usar a fraseologia normalizada para transmitir um estado claro e estruturado do sinistrado, permitindo uma resposta médica rápida e adequada","Só contactar a assistência médica se o estado piorar","Transmitir apenas o nome do sinistrado num primeiro momento"], correct:1, expl:"A fraseologia normalizada permite uma transmissão rápida e sem ambiguidade do estado do doente, condição essencial para receber um aconselhamento médico adequado o mais rapidamente possível." },
      { q:"O aconselhamento médico por rádio recomenda uma vigilância apertada enquanto se aguarda uma decisão sobre uma eventual evacuação médica. Qual é o reflexo correto para a equipa a bordo?", opts:["Considerar que o papel da equipa termina após a transmissão do aconselhamento médico","Continuar uma vigilância ativa e estruturada do estado do doente, documentando qualquer evolução para informar os cuidados seguintes","Esperar passivamente sem reavaliar o estado do doente","Cessar toda a comunicação com a assistência médica por rádio até à escala"], correct:1, expl:"A vigilância ativa e a documentação contínua do estado do doente permitem informar eficazmente qualquer decisão posterior, incluindo uma eventual evacuação médica." },
    ],
  },

  // ══════════════════════════════════════
  // THEME 5 — Abandon ship under compounding conditions
  // (Heavy weather + Degraded stability + Lifeboats/liferafts + Survival leadership)
  // ══════════════════════════════════════
  theme5_abandon_ship: {
    fr: [
      { q:"Un navire subit une avarie de stabilité sévère alors qu'une tempête se renforce. La décision d'abandon du navire est prise. Quelle est la priorité immédiate de l'équipe de pont dans ce contexte dégradé ?", opts:["Continuer à essayer de corriger la stabilité indéfiniment avant tout abandon","Exécuter la procédure d'abandon du navire de manière structurée, en tenant compte des conditions météo dégradées pour le choix et le lancement des embarcations","Attendre une amélioration de la météo avant d'agir","Laisser chaque membre d'équipage décider individuellement de la marche à suivre"], correct:1, expl:"Une fois la décision d'abandon prise, l'exécution structurée prime — les conditions météo dégradées doivent être intégrées dans le choix et le déroulement de la mise à l'eau, sans attendre une amélioration hypothétique." },
      { q:"Dans des conditions de mer forte, le lancement d'une embarcation de sauvetage présente des risques accrus. Quel principe doit guider l'équipe ?", opts:["Lancer l'embarcation le plus vite possible sans considération de méthode","Respecter rigoureusement la procédure de mise à l'eau malgré la pression du temps — une exécution précipitée sous mer forte augmente le risque d'échec","Renoncer totalement à l'utilisation des embarcations si la mer est forte","Improviser une méthode différente de celle entraînée"], correct:1, expl:"La rigueur procédurale reste essentielle même sous pression — une exécution précipitée dans des conditions déjà dégradées augmente significativement le risque d'échec de la manœuvre." },
      { q:"Une fois à bord d'un radeau de survie, un membre d'équipage prend naturellement le rôle de leader informel. Quelle attitude reflète un bon leadership de survie dans ce contexte ?", opts:["Imposer des décisions sans jamais écouter les préoccupations des autres survivants","Organiser clairement les tâches essentielles (veille, gestion des ressources, moral du groupe) tout en restant à l'écoute de l'équipe","Rester passif et laisser chacun agir de son côté","Se concentrer uniquement sur sa propre survie individuelle"], correct:1, expl:"Un leadership de survie efficace organise clairement les tâches essentielles tout en maintenant une écoute active du groupe — un équilibre entre structure et attention humaine." },
      { q:"Après l'abandon du navire, la situation semble stabilisée sur le radeau de survie. Quel réflexe de sécurité reste néanmoins essentiel ?", opts:["Considérer que la phase critique est terminée et relâcher toute vigilance","Continuer à surveiller activement l'état du groupe, les conditions météo et signaler la position dès que possible, la vigilance restant essentielle après l'abandon","Attendre passivement le secours sans action supplémentaire","Se reposer sans organiser aucune veille"], correct:1, expl:"L'abandon du navire ne marque pas la fin du danger — la vigilance active (état du groupe, météo, signalisation de la position) reste essentielle jusqu'au secours effectif." },
    ],
    en: [
      { q:"A vessel suffers a severe stability failure while a storm intensifies. The decision to abandon ship is made. What is the deck team's immediate priority in this degraded context?", opts:["Keep trying to correct stability indefinitely before any abandonment","Execute the abandon-ship procedure in a structured way, factoring the deteriorated weather into the choice and launching of the survival craft","Wait for the weather to improve before acting","Let each crew member individually decide how to proceed"], correct:1, expl:"Once the abandonment decision is made, structured execution takes priority — the deteriorated weather must be factored into the choice and conduct of the launch, without waiting for a hypothetical improvement." },
      { q:"In heavy seas, launching a lifeboat carries increased risk. What principle should guide the team?", opts:["Launch the boat as fast as possible regardless of method","Rigorously follow the launching procedure despite time pressure — a rushed execution in heavy seas increases the risk of failure","Give up entirely on using the boats if the sea is heavy","Improvise a different method from the one trained"], correct:1, expl:"Procedural rigor remains essential even under pressure — a rushed execution in already-degraded conditions significantly increases the risk of the maneuver failing." },
      { q:"Once aboard a liferaft, a crew member naturally takes on an informal leader role. What attitude reflects good survival leadership in this context?", opts:["Impose decisions without ever listening to other survivors' concerns","Clearly organize essential tasks (watch, resource management, group morale) while remaining attentive to the team","Stay passive and let everyone act on their own","Focus solely on one's own individual survival"], correct:1, expl:"Effective survival leadership clearly organizes essential tasks while maintaining active listening with the group — a balance between structure and human attentiveness." },
      { q:"After abandoning ship, the situation seems stabilized on the liferaft. What safety reflex nevertheless remains essential?", opts:["Consider the critical phase over and relax all vigilance","Continue actively monitoring the group's condition, the weather, and signal position as soon as possible — vigilance remains essential after abandonment","Wait passively for rescue without further action","Rest without organizing any watch"], correct:1, expl:"Abandoning ship does not mark the end of danger — active vigilance (group condition, weather, signaling position) remains essential until actual rescue." },
    ],
    es: [
      { q:"Un buque sufre una avería grave de estabilidad mientras una tormenta se intensifica. Se toma la decisión de abandonar el buque. ¿Cuál es la prioridad inmediata del equipo de cubierta en este contexto degradado?", opts:["Seguir intentando corregir la estabilidad indefinidamente antes de cualquier abandono","Ejecutar el procedimiento de abandono del buque de forma estructurada, teniendo en cuenta el tiempo degradado para la elección y el lanzamiento de las embarcaciones","Esperar a que mejore el tiempo antes de actuar","Dejar que cada miembro de la tripulación decida individualmente cómo proceder"], correct:1, expl:"Una vez tomada la decisión de abandono, la ejecución estructurada tiene prioridad — el tiempo degradado debe integrarse en la elección y el desarrollo del lanzamiento, sin esperar una mejora hipotética." },
      { q:"Con mar gruesa, el lanzamiento de un bote salvavidas presenta riesgos añadidos. ¿Qué principio debe guiar al equipo?", opts:["Lanzar el bote lo más rápido posible sin considerar el método","Respetar rigurosamente el procedimiento de lanzamiento pese a la presión del tiempo — una ejecución precipitada con mar gruesa aumenta el riesgo de fallo","Renunciar por completo al uso de los botes si el mar está grueso","Improvisar un método distinto del entrenado"], correct:1, expl:"El rigor procedimental sigue siendo esencial incluso bajo presión — una ejecución precipitada en condiciones ya degradadas aumenta significativamente el riesgo de que la maniobra falle." },
      { q:"Una vez a bordo de una balsa salvavidas, un miembro de la tripulación asume de forma natural un papel de líder informal. ¿Qué actitud refleja un buen liderazgo de supervivencia en este contexto?", opts:["Imponer decisiones sin escuchar nunca las preocupaciones de los demás supervivientes","Organizar claramente las tareas esenciales (vigilancia, gestión de recursos, moral del grupo) manteniéndose atento al equipo","Permanecer pasivo y dejar que cada uno actúe por su cuenta","Centrarse únicamente en la propia supervivencia individual"], correct:1, expl:"Un liderazgo de supervivencia eficaz organiza claramente las tareas esenciales manteniendo a la vez una escucha activa del grupo — un equilibrio entre estructura y atención humana." },
      { q:"Tras el abandono del buque, la situación parece estabilizada en la balsa salvavidas. ¿Qué reflejo de seguridad sigue siendo esencial?", opts:["Considerar terminada la fase crítica y relajar toda vigilancia","Seguir vigilando activamente el estado del grupo, el tiempo, y señalar la posición en cuanto sea posible — la vigilancia sigue siendo esencial tras el abandono","Esperar pasivamente el rescate sin ninguna acción adicional","Descansar sin organizar ninguna guardia"], correct:1, expl:"El abandono del buque no marca el fin del peligro — la vigilancia activa (estado del grupo, tiempo, señalización de la posición) sigue siendo esencial hasta el rescate efectivo." },
    ],
    pt: [
      { q:"Um navio sofre uma avaria grave de estabilidade enquanto uma tempestade se intensifica. É tomada a decisão de abandonar o navio. Qual é a prioridade imediata da equipa de convés neste contexto degradado?", opts:["Continuar a tentar corrigir a estabilidade indefinidamente antes de qualquer abandono","Executar o procedimento de abandono do navio de forma estruturada, tendo em conta o tempo degradado na escolha e no lançamento das embarcações","Esperar que o tempo melhore antes de agir","Deixar que cada membro da tripulação decida individualmente como proceder"], correct:1, expl:"Uma vez tomada a decisão de abandono, a execução estruturada tem prioridade — o tempo degradado deve ser integrado na escolha e no desenrolar do lançamento, sem esperar por uma melhoria hipotética." },
      { q:"Com mar grosso, o lançamento de um bote salva-vidas apresenta riscos acrescidos. Que princípio deve orientar a equipa?", opts:["Lançar o bote o mais rápido possível sem considerar o método","Respeitar rigorosamente o procedimento de lançamento apesar da pressão do tempo — uma execução precipitada com mar grosso aumenta o risco de falha","Renunciar totalmente ao uso dos botes se o mar estiver grosso","Improvisar um método diferente do treinado"], correct:1, expl:"O rigor processual continua a ser essencial mesmo sob pressão — uma execução precipitada em condições já degradadas aumenta significativamente o risco de a manobra falhar." },
      { q:"Uma vez a bordo de uma balsa salva-vidas, um membro da tripulação assume naturalmente um papel de líder informal. Que atitude reflete uma boa liderança de sobrevivência neste contexto?", opts:["Impor decisões sem nunca ouvir as preocupações dos outros sobreviventes","Organizar claramente as tarefas essenciais (vigia, gestão de recursos, moral do grupo) mantendo-se atento à equipa","Permanecer passivo e deixar que cada um aja por conta própria","Concentrar-se apenas na própria sobrevivência individual"], correct:1, expl:"Uma liderança de sobrevivência eficaz organiza claramente as tarefas essenciais mantendo ao mesmo tempo uma escuta ativa do grupo — um equilíbrio entre estrutura e atenção humana." },
      { q:"Após o abandono do navio, a situação parece estabilizada na balsa salva-vidas. Que reflexo de segurança continua no entanto essencial?", opts:["Considerar terminada a fase crítica e relaxar toda a vigilância","Continuar a vigiar ativamente o estado do grupo, o tempo, e sinalizar a posição assim que possível — a vigilância continua essencial após o abandono","Esperar passivamente pelo resgate sem qualquer ação adicional","Descansar sem organizar qualquer vigia"], correct:1, expl:"O abandono do navio não marca o fim do perigo — a vigilância ativa (estado do grupo, tempo, sinalização da posição) continua essencial até ao resgate efetivo." },
    ],
  },

  // ══════════════════════════════════════
  // THEME 6 — Restricted visibility navigational hazard
  // (IALA/sound signals + COLREG restricted visibility + VHF/AIS + Hazard recognition)
  // ══════════════════════════════════════
  theme6_restricted_visibility: {
    fr: [
      { q:"En visibilité réduite, un contact radar est détecté. Son relèvement compas reste constant pendant que la distance diminue. Que signifie cette observation ?", opts:["Le contact s'éloigne, aucune action n'est nécessaire","Un risque de collision existe — un relèvement constant avec distance qui diminue est un signe classique de risque de collision","Le contact a changé de cap récemment","Il faut ignorer ce contact car il est probablement à l'arrêt"], correct:1, expl:"Un relèvement (compas ou radar) qui ne varie pas de façon appréciable pendant qu'un navire se rapproche est un indicateur classique de risque de collision — cette observation impose une veille renforcée et une préparation à manœuvrer." },
      { q:"Un signal sonore de brouillard est entendu à l'avant, sans contact radar clairement identifié. Quelle est la conduite à tenir ?", opts:["Ignorer le signal si le radar ne montre rien de clair","Réduire immédiatement la vitesse et se tenir prêt à manœuvrer, en renforçant la veille par tous les moyens disponibles","Répondre par un signal sonore identique sans autre action","Changer de cap sans évaluation de la situation"], correct:1, expl:"Un signal sonore de brouillard sans contact radar clair impose une prudence maximale — réduction de vitesse et disponibilité immédiate à manœuvrer, en renforçant la veille par tous les moyens." },
      { q:"La communication VHF avec un navire proche en visibilité réduite reste incertaine, sans confirmation claire des intentions réciproques. Quel réflexe s'impose ?", opts:["Supposer que l'autre navire agira de manière prévisible sans confirmation","Ne jamais fonder une décision de manœuvre sur une hypothèse non confirmée — poursuivre les tentatives de communication et se préparer à manœuvrer selon les règles applicables","Cesser toute tentative de communication après un seul essai","Attendre une confirmation avant toute préparation à manœuvrer"], correct:1, expl:"L'absence de confirmation claire des intentions impose de ne jamais bâtir une décision sur une hypothèse non vérifiée — il faut continuer à chercher la confirmation tout en se préparant à manœuvrer selon les règles." },
    ],
    en: [
      { q:"In reduced visibility, a radar contact is detected. Its compass bearing stays constant while the range decreases. What does this observation mean?", opts:["The contact is moving away, no action is needed","A collision risk exists — a steady bearing with decreasing range is a classic sign of collision risk","The contact has recently changed course","The contact should be ignored as it is probably stationary"], correct:1, expl:"A bearing (compass or radar) that does not appreciably change while a vessel is closing is a classic collision-risk indicator — this observation requires reinforced watch and readiness to maneuver." },
      { q:"A fog signal is heard ahead, without a clearly identified radar contact. What is the correct conduct?", opts:["Ignore the signal if radar shows nothing clear","Immediately reduce speed and be ready to maneuver, reinforcing the watch by every available means","Respond with an identical sound signal without any other action","Change course without assessing the situation"], correct:1, expl:"A fog signal without a clear radar contact demands maximum caution — reducing speed and being immediately ready to maneuver, while reinforcing the watch by every available means." },
      { q:"VHF communication with a nearby vessel in reduced visibility remains uncertain, with no clear confirmation of mutual intentions. What reflex is required?", opts:["Assume the other vessel will act predictably without confirmation","Never base a maneuvering decision on an unconfirmed assumption — keep attempting communication and prepare to maneuver according to the applicable rules","Stop all communication attempts after a single try","Wait for confirmation before any preparation to maneuver"], correct:1, expl:"The absence of clear confirmation of intentions means a decision must never be built on an unverified assumption — communication attempts must continue while preparing to maneuver according to the rules." },
    ],
    es: [
      { q:"Con visibilidad reducida, se detecta un contacto de radar. Su marcación de compás se mantiene constante mientras la distancia disminuye. ¿Qué significa esta observación?", opts:["Se aleja, no se necesita ninguna acción","Existe un riesgo de colisión — una marcación constante con distancia que disminuye es un indicio clásico de riesgo de colisión","Ha cambiado de rumbo recientemente","Hay que ignorarlo porque probablemente está detenido"], correct:1, expl:"Una marcación (de compás o radar) que no varía de forma apreciable mientras un buque se acerca es un indicador clásico de riesgo de colisión — esta observación exige una vigilancia reforzada y prepararse para maniobrar." },
      { q:"Se oye una señal de niebla por proa, sin un contacto radar claramente identificado. ¿Cuál es la conducta a seguir?", opts:["Ignorar la señal si el radar no muestra nada claro","Reducir de inmediato la velocidad y estar listo para maniobrar, reforzando la vigilancia por todos los medios disponibles","Responder con una señal acústica idéntica sin ninguna otra acción","Cambiar de rumbo sin evaluar la situación"], correct:1, expl:"Una señal de niebla sin un contacto radar claro exige la máxima prudencia — reducir la velocidad y estar listo de inmediato para maniobrar, reforzando la vigilancia por todos los medios disponibles." },
      { q:"La comunicación VHF con un buque cercano en visibilidad reducida sigue siendo incierta, sin confirmación clara de las intenciones mutuas. ¿Qué reflejo se impone?", opts:["Suponer que el otro buque actuará de forma previsible sin confirmación","Nunca basar una decisión de maniobra en una suposición no confirmada — seguir intentando comunicarse y prepararse para maniobrar según las reglas aplicables","Dejar de intentar comunicarse tras un solo intento","Esperar confirmación antes de cualquier preparación para maniobrar"], correct:1, expl:"La ausencia de confirmación clara de las intenciones exige no basar nunca una decisión en una suposición no verificada — hay que seguir intentando comunicarse mientras se prepara la maniobra según las reglas." },
    ],
    pt: [
      { q:"Em visibilidade reduzida, é detetado um contacto de radar. A sua marcação de bússola mantém-se constante enquanto a distância diminui. O que significa esta observação?", opts:["Está a afastar-se, nenhuma ação é necessária","Existe um risco de colisão — uma marcação constante com distância a diminuir é um sinal clássico de risco de colisão","Mudou de rumo recentemente","Deve ignorar-se este contacto pois provavelmente está parado"], correct:1, expl:"Uma marcação (de bússola ou radar) que não varia de forma apreciável enquanto um navio se aproxima é um indicador clássico de risco de colisão — esta observação exige uma vigilância reforçada e preparação para manobrar." },
      { q:"Ouve-se um sinal de nevoeiro à proa, sem um contacto radar claramente identificado. Qual é a conduta a adotar?", opts:["Ignorar o sinal se o radar não mostrar nada claro","Reduzir de imediato a velocidade e estar pronto para manobrar, reforçando a vigia por todos os meios disponíveis","Responder com um sinal sonoro idêntico sem qualquer outra ação","Mudar de rumo sem avaliar a situação"], correct:1, expl:"Um sinal de nevoeiro sem um contacto radar claro exige o máximo de prudência — reduzir a velocidade e estar imediatamente pronto para manobrar, reforçando a vigia por todos os meios disponíveis." },
      { q:"A comunicação VHF com um navio próximo em visibilidade reduzida continua incerta, sem confirmação clara das intenções mútuas. Que reflexo se impõe?", opts:["Supor que o outro navio agirá de forma previsível sem confirmação","Nunca basear uma decisão de manobra numa suposição não confirmada — continuar as tentativas de comunicação e preparar-se para manobrar segundo as regras aplicáveis","Deixar de tentar comunicar após uma única tentativa","Esperar confirmação antes de qualquer preparação para manobrar"], correct:1, expl:"A ausência de confirmação clara das intenções exige nunca basear uma decisão numa suposição não verificada — é preciso continuar a procurar a confirmação enquanto se prepara para manobrar segundo as regras." },
    ],
  },
};
