// ── lessonRegistry.ts ──────────────────────────────────────────
// This registry is the single source of truth for all lesson metadata used by MAP.
//
// Fondation V2/V3 : ce fichier ne contient qu'un modèle de données et deux
// exemples de compilation. Il n'est importé nulle part ailleurs dans MAP en V1.
// Aucune leçon existante n'est modifiée, aucune UI n'affiche ces données,
// aucun comportement actuel de MAP ne dépend de ce fichier.
//
// Vocation future (non implémentée aujourd'hui) : Exam Center, Certificates MAP,
// Badges, Learning Roadmap, Career Advisor, Progress Analytics, STCW Mapping,
// recommandations IA. Le futur Maritime Lexicon utilisera aussi les IDs de ce
// registre (lessonIds, moduleIds) plutôt que des chaînes de caractères libres -
// mais LexiqueMaritime.tsx n'est pas modifié aujourd'hui.

import type { RankId } from "./rankRegistry";
import type { VesselTypeId } from "./vesselTypeRegistry";

export type LessonId = string;

export interface LessonRegistryItem {
  lessonId: LessonId;
  department: "deck" | "engine" | "safety";
  moduleId: string;

  difficulty: "foundation" | "intermediate" | "advanced";

  targetRanks: RankId[];
  vesselTypes: VesselTypeId[];

  stcwReference: string[];

  requiredForExam: boolean;
  recommendedForPromotion: boolean;

  examCategory: string[];
  badgeCategory: string[];
  certificateCategory: string[];

  estimatedStudyMinutes?: number;
  estimatedExamWeight?: number;

  prerequisites: LessonId[];
  recommendedBefore: LessonId[];
  recommendedAfter: LessonId[];

  status: "draft" | "active" | "deprecated";
}

// Registre indexé par lessonId. Stale note removed 2026-09-01: this used to
// say "empty except two compile-check examples" — long outdated, the
// registry has 133 real entries as of the same-day meteo/colreg id cleanup
// (deck_meteo_l1-l7 renamed to d7-l1..d7-l7; deck_colreg_l1, an orphan with
// no real MODULES correspondence — the real COLREG lesson is "d1-l8" — was
// deleted outright, not renamed, since renaming it would have collided with
// that already-existing, already-correct entry).
export const LESSON_REGISTRY: Record<LessonId, LessonRegistryItem> = {
  // Renamed from deck_meteo_l1-l7 (2026-09-01, on explicit request): the old
  // free-text lessonId had no correspondence with Dashboard.tsx's MODULES,
  // even though moduleId already correctly said "d7" — MaritimeApp.tsx
  // already calls markLessonCompleted("d7-l1")..("d7-l7") for these real
  // lessons (lines ~3891-3940), and LessonProgressBadge.tsx already maps to
  // the same "d7-lN" ids — this rename makes lessonId match what the app
  // already tracks, not a new convention invented here.
  "d7-l1": {
    lessonId: "d7-l1",
    department: "deck",
    moduleId: "d7",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d7-l2": {
    lessonId: "d7-l2",
    department: "deck",
    moduleId: "d7",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: ["d7-l1"],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d7-l3": {
    lessonId: "d7-l3",
    department: "deck",
    moduleId: "d7",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: ["d7-l2"],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d7-l4": {
    lessonId: "d7-l4",
    department: "deck",
    moduleId: "d7",
    difficulty: "intermediate",
    targetRanks: ["oow", "chief_officer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: ["d7-l3"],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d7-l5": {
    lessonId: "d7-l5",
    department: "deck",
    moduleId: "d7",
    difficulty: "intermediate",
    targetRanks: ["oow", "chief_officer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: ["d7-l4"],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d7-l6": {
    lessonId: "d7-l6",
    department: "deck",
    moduleId: "d7",
    difficulty: "intermediate",
    targetRanks: ["oow", "chief_officer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: ["d7-l5"],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d7-l7": {
    lessonId: "d7-l7",
    department: "deck",
    moduleId: "d7",
    difficulty: "advanced",
    targetRanks: ["oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: ["d7-l6"],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e1-l1": {
    lessonId: "e1-l1",
    department: "engine",
    moduleId: "e1",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e1-l2": {
    lessonId: "e1-l2",
    department: "engine",
    moduleId: "e1",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e1-l3": {
    lessonId: "e1-l3",
    department: "engine",
    moduleId: "e1",
    difficulty: "intermediate",
    targetRanks: ["engine_cadet", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e1-l4": {
    lessonId: "e1-l4",
    department: "engine",
    moduleId: "e1",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e1-l5": {
    lessonId: "e1-l5",
    department: "engine",
    moduleId: "e1",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e1-l6": {
    lessonId: "e1-l6",
    department: "engine",
    moduleId: "e1",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e1-l7": {
    lessonId: "e1-l7",
    department: "engine",
    moduleId: "e1",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e1-l8": {
    lessonId: "e1-l8",
    department: "engine",
    moduleId: "e1",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e2-l1": {
    lessonId: "e2-l1",
    department: "engine",
    moduleId: "e2",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e2-l2": {
    lessonId: "e2-l2",
    department: "engine",
    moduleId: "e2",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e2-l3": {
    lessonId: "e2-l3",
    department: "engine",
    moduleId: "e2",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e2-l4": {
    lessonId: "e2-l4",
    department: "engine",
    moduleId: "e2",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e2-l5": {
    lessonId: "e2-l5",
    department: "engine",
    moduleId: "e2",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e2-l6": {
    lessonId: "e2-l6",
    department: "engine",
    moduleId: "e2",
    difficulty: "intermediate",
    targetRanks: ["engine_cadet", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e2-l7": {
    lessonId: "e2-l7",
    department: "engine",
    moduleId: "e2",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e3-l1": {
    lessonId: "e3-l1",
    department: "engine",
    moduleId: "boilers_steam_systems",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e3-l2": {
    lessonId: "e3-l2",
    department: "engine",
    moduleId: "e3",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e3-l3": {
    lessonId: "e3-l3",
    department: "engine",
    moduleId: "e3",
    difficulty: "intermediate",
    targetRanks: ["engine_cadet", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e3-l4": {
    lessonId: "e3-l4",
    department: "engine",
    moduleId: "e3",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e3-l5": {
    lessonId: "e3-l5",
    department: "engine",
    moduleId: "e3",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e3-l6": {
    lessonId: "e3-l6",
    department: "engine",
    moduleId: "e3",
    difficulty: "intermediate",
    targetRanks: ["engine_cadet", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e4-l1": {
    lessonId: "e4-l1",
    department: "engine",
    moduleId: "e4",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e4-l2": {
    lessonId: "e4-l2",
    department: "engine",
    moduleId: "e4",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e4-l3": {
    lessonId: "e4-l3",
    department: "engine",
    moduleId: "e4",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e4-l4": {
    lessonId: "e4-l4",
    department: "engine",
    moduleId: "e4",
    difficulty: "intermediate",
    targetRanks: ["engine_cadet", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e4-l5": {
    lessonId: "e4-l5",
    department: "engine",
    moduleId: "e4",
    difficulty: "intermediate",
    targetRanks: ["engine_cadet", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e4-l6": {
    lessonId: "e4-l6",
    department: "engine",
    moduleId: "e4",
    difficulty: "advanced",
    targetRanks: ["engine_cadet", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e5-l1": {
    lessonId: "e5-l1",
    department: "engine",
    moduleId: "e5",
    difficulty: "intermediate",
    targetRanks: ["engine_cadet", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e5-l2": {
    lessonId: "e5-l2",
    department: "engine",
    moduleId: "e5",
    difficulty: "intermediate",
    targetRanks: ["engine_cadet", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e5-l3": {
    lessonId: "e5-l3",
    department: "engine",
    moduleId: "e5",
    difficulty: "intermediate",
    targetRanks: ["engine_cadet", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e5-l4": {
    lessonId: "e5-l4",
    department: "engine",
    moduleId: "e5",
    difficulty: "intermediate",
    targetRanks: ["engine_cadet", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e5-l5": {
    lessonId: "e5-l5",
    department: "engine",
    moduleId: "e5",
    difficulty: "intermediate",
    targetRanks: ["engine_cadet", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e6-l1": {
    lessonId: "e6-l1",
    department: "engine",
    moduleId: "e6",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e6-l2": {
    lessonId: "e6-l2",
    department: "engine",
    moduleId: "e6",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e6-l3": {
    lessonId: "e6-l3",
    department: "engine",
    moduleId: "e6",
    difficulty: "intermediate",
    targetRanks: ["engine_cadet", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e6-l4": {
    lessonId: "e6-l4",
    department: "engine",
    moduleId: "e6",
    difficulty: "intermediate",
    targetRanks: ["engine_cadet", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e6-l5": {
    lessonId: "e6-l5",
    department: "engine",
    moduleId: "e6",
    difficulty: "foundation",
    targetRanks: ["engine_cadet", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e6-l6": {
    lessonId: "e6-l6",
    department: "engine",
    moduleId: "e6",
    difficulty: "intermediate",
    targetRanks: ["engine_cadet", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e7-l1": {
    lessonId: "e7-l1",
    department: "engine",
    moduleId: "e7",
    difficulty: "advanced",
    targetRanks: ["engine_cadet", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e7-l2": {
    lessonId: "e7-l2",
    department: "engine",
    moduleId: "e7",
    difficulty: "advanced",
    targetRanks: ["engine_cadet", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e7-l3": {
    lessonId: "e7-l3",
    department: "engine",
    moduleId: "e7",
    difficulty: "advanced",
    targetRanks: ["engine_cadet", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e7-l4": {
    lessonId: "e7-l4",
    department: "engine",
    moduleId: "e7",
    difficulty: "advanced",
    targetRanks: ["engine_cadet", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "e7-l5": {
    lessonId: "e7-l5",
    department: "engine",
    moduleId: "e7",
    difficulty: "advanced",
    targetRanks: ["engine_cadet", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d1-l1": {
    lessonId: "d1-l1",
    department: "deck",
    moduleId: "d1",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: true,
    recommendedForPromotion: false,
    examCategory: ["foundation"],
    badgeCategory: [],
    certificateCategory: [],
    estimatedExamWeight: 10,
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d1-l2": {
    lessonId: "d1-l2",
    department: "deck",
    moduleId: "d1",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: true,
    recommendedForPromotion: false,
    examCategory: ["foundation"],
    badgeCategory: [],
    certificateCategory: [],
    estimatedExamWeight: 10,
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d1-l3": {
    lessonId: "d1-l3",
    department: "deck",
    moduleId: "d1",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: true,
    recommendedForPromotion: false,
    examCategory: ["foundation"],
    badgeCategory: [],
    certificateCategory: [],
    estimatedExamWeight: 10,
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d1-l4": {
    lessonId: "d1-l4",
    department: "deck",
    moduleId: "d1",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: true,
    recommendedForPromotion: false,
    examCategory: ["foundation"],
    badgeCategory: [],
    certificateCategory: [],
    estimatedExamWeight: 10,
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d1-l5": {
    lessonId: "d1-l5",
    department: "deck",
    moduleId: "d1",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: true,
    recommendedForPromotion: false,
    examCategory: ["foundation"],
    badgeCategory: [],
    certificateCategory: [],
    estimatedExamWeight: 10,
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d1-l6": {
    lessonId: "d1-l6",
    department: "deck",
    moduleId: "d1",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: true,
    recommendedForPromotion: false,
    examCategory: ["foundation"],
    badgeCategory: [],
    certificateCategory: [],
    estimatedExamWeight: 10,
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d1-l7": {
    lessonId: "d1-l7",
    department: "deck",
    moduleId: "d1",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: true,
    recommendedForPromotion: false,
    examCategory: ["foundation"],
    badgeCategory: [],
    certificateCategory: [],
    estimatedExamWeight: 10,
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d1-l8": {
    lessonId: "d1-l8",
    department: "deck",
    moduleId: "d1",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: true,
    recommendedForPromotion: false,
    examCategory: ["foundation"],
    badgeCategory: [],
    certificateCategory: [],
    estimatedExamWeight: 10,
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d1-l9": {
    lessonId: "d1-l9",
    department: "deck",
    moduleId: "d1",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: true,
    recommendedForPromotion: false,
    examCategory: ["foundation"],
    badgeCategory: [],
    certificateCategory: [],
    estimatedExamWeight: 10,
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d1-l10": {
    lessonId: "d1-l10",
    department: "deck",
    moduleId: "d1",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: true,
    recommendedForPromotion: false,
    examCategory: ["foundation"],
    badgeCategory: [],
    certificateCategory: [],
    estimatedExamWeight: 10,
    prerequisites: ["d1-l9"],
    recommendedBefore: ["d3-l2", "d3-l3", "d4-l1"],
    recommendedAfter: [],
    status: "draft",
  },
  "d2-l1": {
    lessonId: "d2-l1",
    department: "deck",
    moduleId: "d2",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d2-l2": {
    lessonId: "d2-l2",
    department: "deck",
    moduleId: "d2",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d2-l3": {
    lessonId: "d2-l3",
    department: "deck",
    moduleId: "d2",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d2-l4": {
    lessonId: "d2-l4",
    department: "deck",
    moduleId: "d2",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d2-l5": {
    lessonId: "d2-l5",
    department: "deck",
    moduleId: "d2",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d2-l6": {
    lessonId: "d2-l6",
    department: "deck",
    moduleId: "d2",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d2-l7": {
    lessonId: "d2-l7",
    department: "deck",
    moduleId: "d2",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d2-l8": {
    lessonId: "d2-l8",
    department: "deck",
    moduleId: "d2",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d2-l9": {
    lessonId: "d2-l9",
    department: "deck",
    moduleId: "d2",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d2-l10": {
    lessonId: "d2-l10",
    department: "deck",
    moduleId: "d2",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d3-l1": {
    lessonId: "d3-l1",
    department: "deck",
    moduleId: "d3",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d3-l2": {
    lessonId: "d3-l2",
    department: "deck",
    moduleId: "d3",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d3-l3": {
    lessonId: "d3-l3",
    department: "deck",
    moduleId: "d3",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d3-l4": {
    lessonId: "d3-l4",
    department: "deck",
    moduleId: "d3",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d3-l5": {
    lessonId: "d3-l5",
    department: "deck",
    moduleId: "d3",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d3-l6": {
    lessonId: "d3-l6",
    department: "deck",
    moduleId: "d3",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d3-l7": {
    lessonId: "d3-l7",
    department: "deck",
    moduleId: "d3",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d4-l1": {
    lessonId: "d4-l1",
    department: "deck",
    moduleId: "d4",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d4-l2": {
    lessonId: "d4-l2",
    department: "deck",
    moduleId: "d4",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d4-l3": {
    lessonId: "d4-l3",
    department: "deck",
    moduleId: "d4",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d4-l4": {
    lessonId: "d4-l4",
    department: "deck",
    moduleId: "d4",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d4-l5": {
    lessonId: "d4-l5",
    department: "deck",
    moduleId: "d4",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d4-l6": {
    lessonId: "d4-l6",
    department: "deck",
    moduleId: "d4",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d4-l7": {
    lessonId: "d4-l7",
    department: "deck",
    moduleId: "d4",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d4-l8": {
    lessonId: "d4-l8",
    department: "deck",
    moduleId: "d4",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d6-l1": {
    lessonId: "d6-l1",
    department: "deck",
    moduleId: "d6",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d6-l2": {
    lessonId: "d6-l2",
    department: "deck",
    moduleId: "d6",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d6-l3": {
    lessonId: "d6-l3",
    department: "deck",
    moduleId: "d6",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d6-l4": {
    lessonId: "d6-l4",
    department: "deck",
    moduleId: "d6",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d6-l5": {
    lessonId: "d6-l5",
    department: "deck",
    moduleId: "d6",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d6-l6": {
    lessonId: "d6-l6",
    department: "deck",
    moduleId: "d6",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: ["d6-l1", "d6-l2", "d6-l3", "d6-l4"],
    recommendedAfter: [],
    status: "draft",
  },
  "d6-l7": {
    lessonId: "d6-l7",
    department: "deck",
    moduleId: "d6",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: ["d6-l6"],
    recommendedAfter: [],
    status: "draft",
  },
  "d5-l1": {
    lessonId: "d5-l1",
    department: "deck",
    moduleId: "d5",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d5-l2": {
    lessonId: "d5-l2",
    department: "deck",
    moduleId: "d5",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d5-l3": {
    lessonId: "d5-l3",
    department: "deck",
    moduleId: "d5",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d5-l4": {
    lessonId: "d5-l4",
    department: "deck",
    moduleId: "d5",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "d5-l5": {
    lessonId: "d5-l5",
    department: "deck",
    moduleId: "d5",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s1-l1": {
    lessonId: "s1-l1",
    department: "safety",
    moduleId: "s1",
    difficulty: "intermediate",
    targetRanks: ["oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s1-l2": {
    lessonId: "s1-l2",
    department: "safety",
    moduleId: "s1",
    difficulty: "intermediate",
    targetRanks: ["oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s1-l3": {
    lessonId: "s1-l3",
    department: "safety",
    moduleId: "s1",
    difficulty: "intermediate",
    targetRanks: ["oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s1-l4": {
    lessonId: "s1-l4",
    department: "safety",
    moduleId: "s1",
    difficulty: "intermediate",
    targetRanks: ["oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s1-l5": {
    lessonId: "s1-l5",
    department: "safety",
    moduleId: "s1",
    difficulty: "intermediate",
    targetRanks: ["oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s1-l6": {
    lessonId: "s1-l6",
    department: "safety",
    moduleId: "s1",
    difficulty: "intermediate",
    targetRanks: ["deck_cadet", "oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s2-l1": {
    lessonId: "s2-l1",
    department: "safety",
    moduleId: "s2",
    difficulty: "intermediate",
    targetRanks: ["oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s2-l2": {
    lessonId: "s2-l2",
    department: "safety",
    moduleId: "s2",
    difficulty: "intermediate",
    targetRanks: ["oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s2-l3": {
    lessonId: "s2-l3",
    department: "safety",
    moduleId: "s2",
    difficulty: "intermediate",
    targetRanks: ["oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s2-l4": {
    lessonId: "s2-l4",
    department: "safety",
    moduleId: "s2",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s2-l5": {
    lessonId: "s2-l5",
    department: "safety",
    moduleId: "s2",
    difficulty: "intermediate",
    targetRanks: ["oow", "chief_officer", "master"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s3-l1": {
    lessonId: "s3-l1",
    department: "safety",
    moduleId: "s3",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s3-l2": {
    lessonId: "s3-l2",
    department: "safety",
    moduleId: "s3",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s3-l3": {
    lessonId: "s3-l3",
    department: "safety",
    moduleId: "s3",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s3-l4": {
    lessonId: "s3-l4",
    department: "safety",
    moduleId: "s3",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s3-l5": {
    lessonId: "s3-l5",
    department: "safety",
    moduleId: "s3",
    difficulty: "intermediate",
    targetRanks: ["oow", "chief_officer", "master", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s3-l6": {
    lessonId: "s3-l6",
    department: "safety",
    moduleId: "s3",
    difficulty: "intermediate",
    targetRanks: ["oow", "chief_officer", "master", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s3-l7": {
    lessonId: "s3-l7",
    department: "safety",
    moduleId: "s3",
    difficulty: "intermediate",
    targetRanks: ["oow", "chief_officer", "master", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s3-l8": {
    lessonId: "s3-l8",
    department: "safety",
    moduleId: "s3",
    difficulty: "intermediate",
    targetRanks: ["oow", "chief_officer", "master", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s4-l1": {
    lessonId: "s4-l1",
    department: "safety",
    moduleId: "s4",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s4-l2": {
    lessonId: "s4-l2",
    department: "safety",
    moduleId: "s4",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s4-l3": {
    lessonId: "s4-l3",
    department: "safety",
    moduleId: "s4",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s4-l4": {
    lessonId: "s4-l4",
    department: "safety",
    moduleId: "s4",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s4-l5": {
    lessonId: "s4-l5",
    department: "safety",
    moduleId: "s4",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s4-l6": {
    lessonId: "s4-l6",
    department: "safety",
    moduleId: "s4",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s4-l7": {
    lessonId: "s4-l7",
    department: "safety",
    moduleId: "s4",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s5-l1": {
    lessonId: "s5-l1",
    department: "safety",
    moduleId: "s5",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s5-l2": {
    lessonId: "s5-l2",
    department: "safety",
    moduleId: "s5",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s5-l3": {
    lessonId: "s5-l3",
    department: "safety",
    moduleId: "s5",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s5-l4": {
    lessonId: "s5-l4",
    department: "safety",
    moduleId: "s5",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s6-l1": {
    lessonId: "s6-l1",
    department: "safety",
    moduleId: "s6",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s6-l2": {
    lessonId: "s6-l2",
    department: "safety",
    moduleId: "s6",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s6-l3": {
    lessonId: "s6-l3",
    department: "safety",
    moduleId: "s6",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s6-l4": {
    lessonId: "s6-l4",
    department: "safety",
    moduleId: "s6",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s6-l5": {
    lessonId: "s6-l5",
    department: "safety",
    moduleId: "s6",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
  "s6-l6": {
    lessonId: "s6-l6",
    department: "safety",
    moduleId: "s6",
    difficulty: "foundation",
    targetRanks: ["deck_cadet", "os", "ab", "bosun", "oow", "chief_officer", "master", "engine_cadet", "wiper", "motorman", "oiler", "fourth_engineer", "third_engineer", "second_engineer", "chief_engineer"],
    vesselTypes: [],
    stcwReference: [],
    requiredForExam: false,
    recommendedForPromotion: false,
    examCategory: [],
    badgeCategory: [],
    certificateCategory: [],
    prerequisites: [],
    recommendedBefore: [],
    recommendedAfter: [],
    status: "draft",
  },
};

export function getLessonMeta(lessonId: LessonId): LessonRegistryItem | undefined {
  return LESSON_REGISTRY[lessonId];
}

// Stub - retourne toujours [] en V1. Logique réelle à implémenter lors de la
// construction d'Exam Center / Learning Roadmap / Career Advisor.
export function getLessonsForRank(_rankId: RankId): LessonRegistryItem[] {
  return [];
}

// Stub - retourne toujours [] en V1. Logique réelle à implémenter lors de la
// construction des modules Specialized Operations / Career Advisor.
export function getLessonsForVessel(_vesselTypeId: VesselTypeId): LessonRegistryItem[] {
  return [];
}
