/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShipTestRouteImport } from './routes/ship-test'
import { Route as IndexRouteImport } from './routes/index'

const ShipTestRoute = ShipTestRouteImport.update({
  id: '/ship-test',
  path: '/ship-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ship-test': typeof ShipTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ship-test': typeof ShipTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ship-test': typeof ShipTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ship-test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ship-test'
  id: '__root__' | '/' | '/ship-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShipTestRoute: typeof ShipTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ship-test': {
      id: '/ship-test'
      path: '/ship-test'
      fullPath: '/ship-test'
      preLoaderRoute: typeof ShipTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShipTestRoute: ShipTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
